# global settings

# ex:
# my_section:
#   some_entry: some_value

# Settings.my_section.some_entry == some_value

app:
  name: RideSnap
  email:
    steven: slstevenlam@gmail.com
    melbs: mclemieux@gmail.com
    tommy: quantumventuress@gmail.com
    brett: brett@dudo.io

google_analytics:
  enabled: false

meta_tags:
  - sell
  - sale
  - car
  - vehicle
  - concierge
  - full service

edmunds:
  base_url: https://api.edmunds.com
  image_url: http://media.ed.edmunds-media.com
  key: g95vdjamaxag9hbg5betrvf9
  secret: VaVD9hB6e2y3npHd2X5eNuTq

locals:
  zip_code: 94102

vehicle_makes:
  am-general: 'AM General'
  acura: 'Acura'
  aston-martin: 'Aston Martin'
  audi: 'Audi'
  bmw: 'BMW'
  bentley: 'Bentley'
  bugatti: 'Bugatti'
  buick: 'Buick'
  cadillac: 'Cadillac'
  chevrolet: 'Chevrolet'
  chrysler: 'Chrysler'
  daewoo: 'Daewoo'
  dodge: 'Dodge'
  eagle: 'Eagle'
  fiat: 'FIAT'
  ferrari: 'Ferrari'
  fisker: 'Fisker'
  ford: 'Ford'
  gmc: 'GMC'
  geo: 'Geo'
  hummer: 'Hummer'
  honda: 'Honda'
  hyundai: 'Hyundai'
  infiniti: 'Infiniti'
  isuzu: 'Isuzu'
  jaguar: 'Jaguar'
  jeep: 'Jeep'
  kia: 'Kia'
  lamborghini: 'Lamborghini'
  land-rover: 'Land Rover'
  lexus: 'Lexus'
  lincoln: 'Lincoln'
  lotus: 'Lotus'
  mini: 'Mini'
  maserati: 'Maserati'
  maybach: 'Maybach'
  mazda: 'Mazda'
  mclaren: 'McLaren'
  mercedes-benz: 'Mercedes-Benz'
  mercury: 'Mercury'
  mitsubishi: 'Mitsubishi'
  nissan: 'Nissan'
  oldsmobile: 'Oldsmobile'
  panoz: 'Panoz'
  plymouth: 'Plymouth'
  pontiac: 'Pontiac'
  porsche: 'Porsche'
  ram: 'Ram'
  rolls-royce: 'Rolls-Royce'
  saab: 'Saab'
  saturn: 'Saturn'
  scion: 'Scion'
  smart: 'Smart'
  spyker: 'Spyker'
  subaru: 'Subaru'
  suzuki: 'Suzuki'
  tesla: 'Tesla'
  toyota: 'Toyota'
  volkswagen: 'Volkswagen'
  volvo: 'Volvo'

social:
  facebook: http://facebook.com
  twitter: http://twitter.com
  linkedin: http://linkedin.com
  google: http://plus.google.com