# global settings

# ex:
# my_section:
#   some_entry: some_value

# Settings.my_section.some_entry == some_value

google_analytics:
  enabled: false

meta_tags:
  - sell
  - sale
  - car
  - vehicle
  - concierge
  - full service

edmunds:
  base_url: https://api.edmunds.com
  image_url: http://media.ed.edmunds-media.com
  key: g95vdjamaxag9hbg5betrvf9
  secret: VaVD9hB6e2y3npHd2X5eNuTq

locals:
  zip_code: 94102