# global settings

# ex:
# my_section:
#   some_entry: some_value

# Settings.my_section.some_entry == some_value

google_analytics:
  enabled: false

meta_tags:
  - sell
  - sale
  - car
  - vehicle
  - concierge
  - full service