# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if Rails.env.development? && Settings.fresh_cars
  50.times do
    mk = Settings.vehicle_makes.to_hash.keys.map(&:to_s).sample
    models = Edmunds.query_models(mk)
    md = models.keys.sample
    yr = Edmunds.query_years(mk, md).keys.reject{ |i| i < Date.today.year-10 }.sample
    next unless yr
    styles = Edmunds.query_styles(mk, md, yr)
    st = styles.keys.sample
    desc = styles[st]
    value = Edmunds.typical_value(st)
    next unless value.kind_of?(Hash)
    sources = [value[:trade_in], value[:private_party]]
    avg = sources.sum / sources.size.to_f
    vl = {}
    vl[:snap_up] = avg.round(-2)
    vl[:trade_in] = value[:trade_in].round(-2)
    vl[:ride_snap] = value[:private_party].round(-2)
    next if vl[:ride_snap].zero?
    @veh = Vehicle.create( make: mk,
                           model: md,
                           model_pretty: models[md],
                           year: yr,
                           style: st,
                           description: desc,
                           mileage: [*1000..200000].sample,
                           preliminary_value: vl,
                           condition: [*1..5].sample,
                           inspection: true,
                           zip_code: Faker::Address.zip_code[0..4] )
    @veh.list!
    sleep 0.3
    puts "#{@veh.info} -- created"
  end
end

dtc = {

  p0001: "Fuel Volume Regulator Control Circuit/Open",
  p0002: "Fuel Volume Regulator Control Circuit Range/Performance",
  p0003: "Fuel Volume Regulator Control Circuit Low",
  p0004: "Fuel Volume Regulator Control Circuit High",
  p0005: "Fuel Shutoff Valve A Control Circuit/Open",
  p0006: "Fuel Shutoff Valve A Control Circuit Low",
  p0007: "Fuel Shutoff Valve A Control Circuit High",
  p0008: "Engine Positions System Performance Bank 1",
  p0009: "Engine Position System Performance Bank 2",
  p0010: "A Camshaft Position Actuator Circuit (Bank 1)",
  p0011: "A Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)",
  p0012: "A Camshaft Position - Timing Over-Retarded (Bank 1)",
  p0013: "B Camshaft Position - Actuator Circuit (Bank 1)",
  p0014: "B Camshaft Position - Timing Over-Advanced or System Performance (Bank 1)",
  p0015: "B Camshaft Position - Timing Over-Retarded (Bank 1)",
  p0016: "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor A)",
  p0017: "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor B)",
  p0018: "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor A)",
  p0019: "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor B)",
  p0020: "A Camshaft Position Actuator Circuit (Bank 2)",
  p0021: "A Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)",
  p0022: "A Camshaft Position - Timing Over-Retarded (Bank 2)",
  p0023: "B Camshaft Position - Actuator Circuit (Bank 2)",
  p0024: "B Camshaft Position - Timing Over-Advanced or System Performance (Bank 2)",
  p0025: "B Camshaft Position - Timing Over-Retarded (Bank 2)",
  p0026: "Intake Valve Control Solenoid Circuit Range/Performance Bank 1",
  p0027: "Exhaust Valve Control solenoid Circuit Range/Performance Bank 1",
  p0028: "Intake valve Control Solenoid Circuit Range/Performance Bank 2",
  p0029: "Exhaust Valve Control Solenoid Circuit Range/Performance Bank 2",
  p0030: "HO2S Heater Control Circuit (Bank 1 Sensor 1)",
  p0031: "HO2S Heater Control Circuit Low (Bank 1 Sensor 1)",
  p0032: "HO2S Heater Control Circuit High (Bank 1 Sensor 1)",
  p0033: "Turbo Charger Bypass Valve Control Circuit",
  p0034: "Turbo Charger Bypass Valve Control Circuit Low",
  p0035: "Turbo Charger Bypass Valve Control Circuit High",
  p0036: "HO2S Heater Control Circuit (Bank 1 Sensor 2)",
  p0037: "HO2S Heater Control Circuit Low (Bank 1 Sensor 2)",
  p0038: "HO2S Heater Control Circuit High (Bank 1 Sensor 2)",
  p0039: "Turbo/Super Charger Bypass Valve Control Circuit Range/Performance",
  p0040: "Upstream Oxygen Sensors Swapped From Bank To Bank",
  p0041: "Downstream Oxygen Sensors Swapped From Bank To Bank",
  p0042: "HO2S Heater Control Circuit (Bank 1 Sensor 3)",
  p0043: "HO2S Heater Control Circuit Low (Bank 1 Sensor 3)",
  p0044: "HO2S Heater Control Circuit High (Bank 1 Sensor 3)",
  p0050: "HO2S Heater Control Circuit (Bank 2 Sensor 1)",
  p0051: "HO2S Heater Control Circuit Low (Bank 2 Sensor 1)",
  p0052: "HO2S Heater Control Circuit High (Bank 2 Sensor 1)",
  p0053: "HO2S Heater Resistance (Bank 1, Sensor 1)",
  p0054: "HO2S Heater Resistance (Bank 1, Sensor 2)",
  p0055: "HO2S Heater Resistance (Bank 1, Sensor 3)",
  p0056: "HO2S Heater Control Circuit (Bank 2 Sensor 2)",
  p0057: "HO2S Heater Control Circuit Low (Bank 2 Sensor 2)",
  p0058: "HO2S Heater Control Circuit High (Bank 2 Sensor 2)",
  p0059: "HO2S Heater Resistance (Bank 2, Sensor 1)",
  p0060: "HO2S Heater Resistance (Bank 2, Sensor 2)",
  p0061: "HO2S Heater Resistance (Bank 2, Sensor 3)",
  p0062: "HO2S Heater Control Circuit (Bank 2 Sensor 3)",
  p0063: "HO2S Heater Control Circuit Low (Bank 2 Sensor 3)",
  p0064: "HO2S Heater Control Circuit High (Bank 2 Sensor 3)",
  p0065: "Air Assisted Injector Control Range/Performance",
  p0066: "Air Assisted Injector Control Circuit or Circuit Low",
  p0067: "Air Assisted Injector Control Circuit High",
  p0068: "MAP/MAF - Throttle Position Correlation",
  p0069: "Manifold Absolute Pressure - Barometric Pressure Correlation",
  p0070: "Ambient Air Temperature Sensor Circuit",
  p0071: "Ambient Air Temperature Sensor Range/Performance",
  p0072: "Ambient Air Temperature Sensor Circuit Low Input",
  p0073: "Ambient Air Temperature Sensor Circuit High Input",
  p0074: "Ambient Air Temperature Sensor Circuit Intermittent",
  p0075: "Intake Valve Control Solenoid Circuit (Bank 1)",
  p0076: "Intake Valve Control Solenoid Circuit Low (Bank 1)",
  p0077: "Intake Valve Control Solenoid Circuit High (Bank 1)",
  p0078: "Exhaust Valve Control Solenoid Circuit (Bank 1)",
  p0079: "Exhaust Valve Control Solenoid Circuit Low (Bank 1)",
  p0080: "Exhaust Valve Control Solenoid Circuit High (Bank 1)",
  p0081: "Intake valve Control Solenoid Circuit (Bank 2)",
  p0082: "Intake Valve Control Solenoid Circuit Low (Bank 2)",
  p0083: "Intake Valve Control Solenoid Circuit High (Bank 2)",
  p0084: "Exhaust Valve Control Solenoid Circuit (Bank 2)",
  p0085: "Exhaust Valve Control Solenoid Circuit Low (Bank 2)",
  p0086: "Exhaust Valve Control Solenoid Circuit High (Bank 2)",
  p0087: "Fuel Rail/System Pressure - Too Low",
  p0088: "Fuel Rail/System Pressure - Too High",
  p0089: "Fuel Pressure Regulator 1 Performance",
  p0090: "Fuel Pressure Regulator 1 Control Circuit",
  p0091: "Fuel Pressure Regulator 1 Control Circuit Low",
  p0092: "Fuel Pressure Regulator 1 Control Circuit High",
  p0093: "Fuel System Leak Detected - Large Leak",
  p0094: "Fuel System Leak Detected - Small Leak",
  p0095: "Intake Air Temperature Sensor 2 Circuit",
  p0096: "Intake Air Temperature Sensor 2 Circuit Range/Performance",
  p0097: "Intake Air Temperature Sensor 2 Circuit Low",
  p0098: "Intake Air Temperature Sensor 2 Circuit High",
  p0099: "Intake Air Temperature Sensor 2 Circuit Intermittent/Errati",
  p0100: "Mass or Volume Air Flow Circuit Malfunction",
  p0101: "Mass or Volume Air Flow Circuit Range/Performance Problem",
  p0102: "Mass or Volume Air Flow Circuit Low Input",
  p0103: "Mass or Volume Air Flow Circuit High Input",
  p0104: "Mass or Volume Air Flow Circuit Intermittent",
  p0105: "Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction",
  p0106: "Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem",
  p0107: "Manifold Absolute Pressure/Barometric Pressure Circuit Low Input",
  p0108: "Manifold Absolute Pressure/Barometric Pressure Circuit High Input",
  p0109: "Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent",
  p0110: "Intake Air Temperature Circuit Malfunction",
  p0111: "Intake Air Temperature Circuit Range/Performance Problem",
  p0112: "Intake Air Temperature Circuit Low Input",
  p0113: "Intake Air Temperature Circuit High Input",
  p0114: "Intake Air Temperature Circuit Intermittent",
  p0115: "Engine Coolant Temperature Circuit Malfunction",
  p0116: "Engine Coolant Temperature Circuit Range/Performance Problem",
  p0117: "Engine Coolant Temperature Circuit Low Input",
  p0118: "Engine Coolant Temperature Circuit High Input",
  p0119: "Engine Coolant Temperature Circuit Intermittent",
  p0120: "Throttle/Petal Position Sensor/Switch A Circuit Malfunction",
  p0121: "Throttle/Petal Position Sensor/Switch A Circuit Range/Performance Problem",
  p0122: "Throttle/Petal Position Sensor/Switch A Circuit Low Input",
  p0123: "Throttle/Petal Position Sensor/Switch A Circuit High Input",
  p0124: "Throttle/Petal Position Sensor/Switch A Circuit Intermittent",
  p0125: "Insufficient Coolant Temperature for Closed Loop Fuel Control",
  p0126: "Insufficient Coolant Temperature for Stable Operation",
  p0130: "O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)",
  p0131: "O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)",
  p0132: "O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)",
  p0133: "O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)",
  p0134: "O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)",
  p0135: "O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)",
  p0136: "O2 Sensor Circuit Malfunction (Bank 1 Sensor 2)",
  p0137: "O2 Sensor Circuit Low Voltage (Bank 1 Sensor 2)",
  p0138: "O2 Sensor Circuit High Voltage (Bank 1 Sensor 2)",
  p0139: "O2 Sensor Circuit Slow Response (Bank 1 Sensor 2)",
  p0140: "O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 2)",
  p0141: "O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)",
  p0142: "O2 Sensor Circuit Malfunction (Bank 1 Sensor 3)",
  p0143: "O2 Sensor Circuit Low Voltage (Bank 1 Sensor 3)",
  p0144: "O2 Sensor Circuit High Voltage (Bank 1 Sensor 3)",
  p0145: "O2 Sensor Circuit Slow Response (Bank 1 Sensor 3)",
  p0146: "O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 3)",
  p0147: "O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 3)",
  p0150: "O2 Sensor Circuit Malfunction (Bank 2 Sensor 1)",
  p0151: "O2 Sensor Circuit Low Voltage (Bank 2 Sensor 1)",
  p0152: "O2 Sensor Circuit High Voltage (Bank 2 Sensor 1)",
  p0153: "O2 Sensor Circuit Slow Response (Bank 2 Sensor 1)",
  p0154: "O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 1)",
  p0155: "O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 1)",
  p0156: "O2 Sensor Circuit Malfunction (Bank 2 Sensor 2)",
  p0157: "O2 Sensor Circuit Low Voltage (Bank 2 Sensor 2)",
  p0158: "O2 Sensor Circuit High Voltage (Bank 2 Sensor 2)",
  p0159: "O2 Sensor Circuit Slow Response (Bank 2 Sensor 2)",
  p0160: "O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 2)",
  p0161: "O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 2)",
  p0162: "O2 Sensor Circuit Malfunction (Bank 2 Sensor 3)",
  p0163: "O2 Sensor Circuit Low Voltage (Bank 2 Sensor 3)",
  p0164: "O2 Sensor Circuit High Voltage (Bank 2 Sensor 3)",
  p0165: "O2 Sensor Circuit Slow Response (Bank 2 Sensor 3)",
  p0166: "O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 3)",
  p0167: "O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 3)",
  p0170: "Fuel Trim Malfunction (Bank 1)",
  p0171: "System too Lean (Bank 1)",
  p0172: "System too Rich (Bank 1)",
  p0173: "Fuel Trim Malfunction (Bank 2)",
  p0174: "System too Lean (Bank 2)",
  p0175: "System too Rich (Bank 2)",
  p0176: "Fuel Composition Sensor Circuit Malfunction",
  p0177: "Fuel Composition Sensor Circuit Range/Performance",
  p0178: "Fuel Composition Sensor Circuit Low Input",
  p0179: "Fuel Composition Sensor Circuit High Input",
  p0180: "Fuel Temperature Sensor A Circuit Malfunction",
  p0181: "Fuel Temperature Sensor A Circuit Range/Performance",
  p0182: "Fuel Temperature Sensor A Circuit Low Input",
  p0183: "Fuel Temperature Sensor A Circuit High Input",
  p0184: "Fuel Temperature Sensor A Circuit Intermittent",
  p0185: "Fuel Temperature Sensor B Circuit Malfunction",
  p0186: "Fuel Temperature Sensor B Circuit Range/Performance",
  p0187: "Fuel Temperature Sensor B Circuit Low Input",
  p0188: "Fuel Temperature Sensor B Circuit High Input",
  p0189: "Fuel Temperature Sensor B Circuit Intermittent",
  p0190: "Fuel Rail Pressure Sensor Circuit Malfunction",
  p0191: "Fuel Rail Pressure Sensor Circuit Range/Performance",
  p0192: "Fuel Rail Pressure Sensor Circuit Low Input",
  p0193: "Fuel Rail Pressure Sensor Circuit High Input",
  p0194: "Fuel Rail Pressure Sensor Circuit Intermittent",
  p0195: "Engine Oil Temperature Sensor Malfunction",
  p0196: "Engine Oil Temperature Sensor Range/Performance",
  p0197: "Engine Oil Temperature Sensor Low",
  p0198: "Engine Oil Temperature Sensor High",
  p0199: "Engine Oil Temperature Sensor Intermittent",
  p0200: "Injector Circuit Malfunction",
  p0201: "Injector Circuit Malfunction - Cylinder 1",
  p0202: "Injector Circuit Malfunction - Cylinder 2",
  p0203: "Injector Circuit Malfunction - Cylinder 3",
  p0204: "Injector Circuit Malfunction - Cylinder 4",
  p0205: "Injector Circuit Malfunction - Cylinder 5",
  p0206: "Injector Circuit Malfunction - Cylinder 6",
  p0207: "Injector Circuit Malfunction - Cylinder 7",
  p0208: "Injector Circuit Malfunction - Cylinder 8",
  p0209: "Injector Circuit Malfunction - Cylinder 9",
  p0210: "Injector Circuit Malfunction - Cylinder 10",
  p0211: "Injector Circuit Malfunction - Cylinder 11",
  p0212: "Injector Circuit Malfunction - Cylinder 12",
  p0213: "Cold Start Injector 1 Malfunction",
  p0214: "Cold Start Injector 2 Malfunction",
  p0215: "Engine Shutoff Solenoid Malfunction",
  p0216: "Injection Timing Control Circuit Malfunction",
  p0217: "Engine Overtemp Condition",
  p0218: "Transmission Over Temperature Condition",
  p0219: "Engine Overspeed Condition",
  p0220: "Throttle/Petal Position Sensor/Switch B Circuit Malfunction",
  p0221: "Throttle/Petal Position Sensor/Switch B Circuit Range/Performance Problem",
  p0222: "Throttle/Petal Position Sensor/Switch B Circuit Low Input",
  p0223: "Throttle/Petal Position Sensor/Switch B Circuit High Input",
  p0224: "Throttle/Petal Position Sensor/Switch B Circuit Intermittent",
  p0225: "Throttle/Petal Position Sensor/Switch C Circuit Malfunction",
  p0226: "Throttle/Petal Position Sensor/Switch C Circuit Range/Performance Problem",
  p0227: "Throttle/Petal Position Sensor/Switch C Circuit Low Input",
  p0228: "Throttle/Petal Position Sensor/Switch C Circuit High Input",
  p0229: "Throttle/Petal Position Sensor/Switch C Circuit Intermittent",
  p0230: "Fuel Pump Primary Circuit Malfunction",
  p0231: "Fuel Pump Secondary Circuit Low",
  p0232: "Fuel Pump Secondary Circuit High",
  p0233: "Fuel Pump Secondary Circuit Intermittent",
  p0234: "Engine Overboost Condition",
  p0235: "Turbocharger Boost Sensor A Circuit Malfunction",
  p0236: "Turbocharger Boost Sensor A Circuit Range/Performance",
  p0237: "Turbocharger Boost Sensor A Circuit Low",
  p0238: "Turbocharger Boost Sensor A Circuit High",
  p0239: "Turbocharger Boost Sensor B Malfunction",
  p0240: "Turbocharger Boost Sensor B Circuit Range/Performance",
  p0241: "Turbocharger Boost Sensor B Circuit Low",
  p0242: "Turbocharger Boost Sensor B Circuit High",
  p0243: "Turbocharger Wastegate Solenoid A Malfunction",
  p0244: "Turbocharger Wastegate Solenoid A Range/Performance",
  p0245: "Turbocharger Wastegate Solenoid A Low",
  p0246: "Turbocharger Wastegate Solenoid A High",
  p0247: "Turbocharger Wastegate Solenoid B Malfunction",
  p0248: "Turbocharger Wastegate Solenoid B Range/Performance",
  p0249: "Turbocharger Wastegate Solenoid B Low",
  p0250: "Turbocharger Wastegate Solenoid B High",
  p0251: "Injection Pump Fuel Metering Control A Malfunction (Cam/Rotor/Injector)",
  p0252: "Injection Pump Fuel Metering Control A Range/Performance (Cam/Rotor/Injector)",
  p0253: "Injection Pump Fuel Metering Control A Low (Cam/Rotor/Injector)",
  p0254: "Injection Pump Fuel Metering Control A High (Cam/Rotor/Injector)",
  p0255: "Injection Pump Fuel Metering Control A Intermittent (Cam/Rotor/Injector)",
  p0256: "Injection Pump Fuel Metering Control B Malfunction (Cam/Rotor/Injector)",
  p0257: "Injection Pump Fuel Metering Control B Range/Performance (Cam/Rotor/Injector)",
  p0258: "Injection Pump Fuel Metering Control B Low (Cam/Rotor/Injector)",
  p0259: "Injection Pump Fuel Metering Control B High (Cam/Rotor/Injector)",
  p0260: "Injection Pump Fuel Metering Control B Intermittent (Cam/Rotor/Injector)",
  p0261: "Cylinder 1 Injector Circuit Low",
  p0262: "Cylinder 1 Injector Circuit High",
  p0263: "Cylinder 1 Contribution/Balance Fault",
  p0264: "Cylinder 2 Injector Circuit Low",
  p0265: "Cylinder 2 Injector Circuit High",
  p0266: "Cylinder 2 Contribution/Balance Fault",
  p0267: "Cylinder 3 Injector Circuit Low",
  p0268: "Cylinder 3 Injector Circuit High",
  p0269: "Cylinder 3 Contribution/Balance Fault",
  p0270: "Cylinder 4 Injector Circuit Low",
  p0271: "Cylinder 4 Injector Circuit High",
  p0272: "Cylinder 4 Contribution/Balance Fault",
  p0273: "Cylinder 5 Injector Circuit Low",
  p0274: "Cylinder 5 Injector Circuit High",
  p0275: "Cylinder S Contribution/Balance Fault",
  p0276: "Cylinder 6 Injector Circuit Low",
  p0277: "Cylinder 6 Injector Circuit High",
  p0278: "Cylinder 6 Contribution/Balance Fault",
  p0279: "Cylinder 7 Injector Circuit Low",
  p0280: "Cylinder 7 Injector Circuit High",
  p0281: "Cylinder 7 Contribution/Balance Fault",
  p0282: "Cylinder 8 Injector Circuit Low",
  p0283: "Cylinder 8 Injector Circuit High",
  p0284: "Cylinder 8 Contribution/Balance Fault",
  p0285: "Cylinder 9 Injector Circuit Low",
  p0286: "Cylinder 9 Injector Circuit High",
  p0287: "Cylinder 9 Contribution/Balance Fault",
  p0288: "Cylinder 10 Injector Circuit Low",
  p0289: "Cylinder 10 Injector Circuit High",
  p0290: "Cylinder 10 Contribution/Balance Fault",
  p0291: "Cylinder 11 Injector Circuit Low",
  p0292: "Cylinder 11 Injector Circuit High",
  p0293: "Cylinder 11 Contribution/Balance Fault",
  p0294: "Cylinder 12 Injector Circuit Low",
  p0295: "Cylinder 12 Injector Circuit High",
  p0296: "Cylinder 12 Contribution/Range Fault",
  p0300: "Random/Multiple Cylinder Misfire Detected",
  p0301: "Cylinder 1 Misfire Detected",
  p0302: "Cylinder 2 Misfire Detected",
  p0303: "Cylinder 3 Misfire Detected",
  p0304: "Cylinder 4 Misfire Detected",
  p0305: "Cylinder 5 Misfire Detected",
  p0306: "Cylinder 6 Misfire Detected",
  p0307: "Cylinder 7 Misfire Detected",
  p0308: "Cylinder 8 Misfire Detected",
  p0309: "Cylinder 9 Misfire Detected",
  p0311: "Cylinder 11 Misfire Detected",
  p0312: "Cylinder 12 Misfire Detected",
  p0320: "Ignition/Distributor Engine Speed Input Circuit Malfunction",
  p0321: "Ignition/Distributor Engine Speed Input Circuit Range/Performance",
  p0322: "Ignition/Distributor Engine Speed Input Circuit No Signal",
  p0323: "Ignition/Distributor Engine Speed Input Circuit Intermittent",
  p0325: "Knock Sensor 1 Circuit Malfunction (Bank 1 or Single Sensor)",
  p0326: "Knock Sensor 1 Circuit Range/Performance (Bank 1 or Single Sensor)",
  p0327: "Knock Sensor 1 Circuit Low Input (Bank 1 or Single Sensor)",
  p0328: "Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)",
  p0329: "Knock Sensor 1 Circuit Intermittent (Bank 1 or Single Sensor)",
  p0330: "Knock Sensor 2 Circuit Malfunction (Bank 2)",
  p0331: "Knock Sensor 2 Circuit Range/Performance (Bank 2)",
  p0332: "Knock Sensor 2 Circuit Low Input (Bank 2)",
  p0333: "Knock Sensor 2 Circuit High Input (Bank 2)",
  p0334: "Knock Sensor 2 Circuit Intermittent (Bank 2)",
  p0335: "Crankshaft Position Sensor A Circuit Malfunction",
  p0336: "Crankshaft Position Sensor A Circuit Range/Performance",
  p0337: "Crankshaft Position Sensor A Circuit Low Input",
  p0338: "Crankshaft Position Sensor A Circuit High Input",
  p0339: "Crankshaft Position Sensor A Circuit Intermittent",
  p0340: "Camshaft Position Sensor Circuit Malfunction",
  p0341: "Camshaft Position Sensor Circuit Range/Performance",
  p0342: "Camshaft Position Sensor Circuit Low Input",
  p0343: "Camshaft Position Sensor Circuit High Input",
  p0344: "Camshaft Position Sensor Circuit Intermittent",
  p0350: "Ignition Coil Primary/Secondary Circuit Malfunction",
  p0351: "Ignition Coil A Primary/Secondary Circuit Malfunction",
  p0352: "Ignition Coil B Primary/Secondary Circuit Malfunction",
  p0353: "Ignition Coil C Primary/Secondary Circuit Malfunction",
  p0354: "Ignition Coil D Primary/Secondary Circuit Malfunction",
  p0355: "Ignition Coil E Primary/Secondary Circuit Malfunction",
  p0356: "Ignition Coil F Primary/Secondary Circuit Malfunction",
  p0357: "Ignition Coil G Primary/Secondary Circuit Malfunction",
  p0358: "Ignition Coil H Primary/Secondary Circuit Malfunction",
  p0359: "Ignition Coil I Primary/Secondary Circuit Malfunction",
  p0360: "Ignition Coil J Primary/Secondary Circuit Malfunction",
  p0361: "Ignition Coil K Primary/Secondary Circuit Malfunction",
  p0362: "Ignition Coil L Primary/Secondary Circuit Malfunction",
  p0370: "Timing Reference High Resolution Signal A Malfunction",
  p0371: "Timing Reference High Resolution Signal A Too Many Pulses",
  p0372: "Timing Reference High Resolution Signal A Too Few Pulses",
  p0373: "Timing Reference High Resolution Signal A Intermittent/Erratic Pulses",
  p0374: "Timing Reference High Resolution Signal A No Pulses",
  p0375: "Timing Reference High Resolution Signal B Malfunction",
  p0376: "Timing Reference High Resolution Signal B Too Many Pulses",
  p0377: "Timing Reference High Resolution Signal B Too Few Pulses",
  p0378: "Timing Reference High Resolution Signal B Intermittent/Erratic Pulses",
  p0379: "Timing Reference High Resolution Signal B No Pulses",
  p0380: "Glow Plug/Heater Circuit A Malfunction",
  p0381: "Glow Plug/Heater Indicator Circuit Malfunction",
  p0382: "Exhaust Gas Recirculation Flow Malfunction",
  p0385: "Crankshaft Position Sensor B Circuit Malfunction",
  p0386: "Crankshaft Position Sensor B Circuit Range/Performance",
  p0387: "Crankshaft Position Sensor B Circuit Low Input",
  p0388: "Crankshaft Position Sensor B Circuit High Input",
  p0389: "Crankshaft Position Sensor B Circuit Intermittent",
  p0400: "Exhaust Gas Recirculation Flow Malfunction",
  p0401: "Exhaust Gas Recirculation Flow Insufficient Detected",
  p0402: "Exhaust Gas Recirculation Flow Excessive Detected",
  p0403: "Exhaust Gas Recirculation Circuit Malfunction",
  p0404: "Exhaust Gas Recirculation Circuit Range/Performance",
  p0405: "Exhaust Gas Recirculation Sensor A Circuit Low",
  p0406: "Exhaust Gas Recirculation Sensor A Circuit High",
  p0407: "Exhaust Gas Recirculation Sensor B Circuit Low",
  p0408: "Exhaust Gas Recirculation Sensor B Circuit High",
  p0410: "Secondary Air Injection System Malfunction",
  p0411: "Secondary Air Injection System Incorrect Flow Detected",
  p0412: "Secondary Air Injection System Switching Valve A Circuit Malfunction",
  p0413: "Secondary Air Injection System Switching Valve A Circuit Open",
  p0414: "Secondary Air Injection System Switching Valve A Circuit Shorted",
  p0415: "Secondary Air Injection System Switching Valve B Circuit Malfunction",
  p0416: "Secondary Air Injection System Switching Valve B Circuit Open",
  p0417: "Secondary Air Injection System Switching Valve B Circuit Shorted",
  p0418: "Secondary Air Injection System Relay A Circuit Malfunction",
  p0419: "Secondary Air Injection System Relay B Circuit Malfunction",
  p0420: "Catalyst System Efficiency Below Threshold (Bank 1)",
  p0421: "Warm Up Catalyst Efficiency Below Threshold (Bank 1)",
  p0422: "Main Catalyst Efficiency Below Threshold (Bank 1)",
  p0423: "Heated Catalyst Efficiency Below Threshold (Bank 1)",
  p0424: "Heated Catalyst Temperature Below Threshold (Bank 1)",
  p0430: "Catalyst System Efficiency Below Threshold (Bank 2)",
  p0431: "Warm Up Catalyst Efficiency Below Threshold (Bank 2)",
  p0432: "Main Catalyst Efficiency Below Threshold (Bank 2)",
  p0433: "Heated Catalyst Efficiency Below Threshold (Bank 2)",
  p0434: "Heated Catalyst Temperature Below Threshold (Bank 2)",
  p0440: "Evaporative Emission Control System Malfunction",
  p0441: "Evaporative Emission Control System Incorrect Purge Flow",
  p0442: "Evaporative Emission Control System Leak Detected (small leak)",
  p0443: "Evaporative Emission Control System Purge Control Valve Circuit",
  p0444: "Evaporative Emission Control System Purge Control Valve Circuit",
  p0445: "Evaporative Emission Control System Purge Control Valve Circuit Shorted",
  p0446: "Evaporative Emission Control System Vent Control Circuit Malfunction",
  p0447: "Evaporative Emission Control System Vent Control Circuit Open",
  p0448: "Evaporative Emission Control System Vent Control Circuit Shorted",
  p0449: "Evaporative Emission Control System Vent Valve/Solenoid Circuit Malfunction",
  p0450: "Evaporative Emission Control System Pressure Sensor Malfunction",
  p0451: "Evaporative Emission Control System Pressure Sensor Range/Performance",
  p0452: "Evaporative Emission Control System Pressure Sensor Low Input",
  p0453: "Evaporative Emission Control System Pressure Sensor High Input",
  p0454: "Evaporative Emission Control System Pressure Sensor Intermittent",
  p0455: "Evaporative Emission Control System Leak Detected (gross leak)",
  p0460: "Fuel Level Sensor Circuit Malfunction",
  p0461: "Fuel Level Sensor Circuit Range/Performance",
  p0462: "Fuel Level Sensor Circuit Low Input",
  p0463: "Fuel Level Sensor Circuit High Input",
  p0464: "Fuel Level Sensor Circuit Intermittent",
  p0465: "Purge Flow Sensor Circuit Malfunction",
  p0466: "Purge Flow Sensor Circuit Range/Performance",
  p0467: "Purge Flow Sensor Circuit Low Input",
  p0468: "Purge Flow Sensor Circuit High Input",
  p0469: "Purge Flow Sensor Circuit Intermittent",
  p0470: "Exhaust Pressure Sensor Malfunction",
  p0471: "Exhaust Pressure Sensor Range/Performance",
  p0472: "Exhaust Pressure Sensor Low",
  p0473: "Exhaust Pressure Sensor High",
  p0474: "Exhaust Pressure Sensor Intermittent",
  p0475: "Exhaust Pressure Control Valve Malfunction",
  p0476: "Exhaust Pressure Control Valve Range/Performance",
  p0477: "Exhaust Pressure Control Valve Low",
  p0478: "Exhaust Pressure Control Valve High",
  p0479: "Exhaust Pressure Control Valve Intermittent",
  p0480: "Cooling Fan 1 Control Circuit Malfunction",
  p0481: "Cooling Fan 2 Control Circuit Malfunction",
  p0482: "Cooling Fan 3 Control Circuit Malfunction",
  p0483: "Cooling Fan Rationality Check Malfunction",
  p0484: "Cooling Fan Circuit Over Current",
  p0485: "Cooling Fan Power/Ground Circuit Malfunction",
  p0500: "Vehicle Speed Sensor Malfunction",
  p0501: "Vehicle Speed Sensor Range/Performance",
  p0502: "Vehicle Speed Sensor Low Input",
  p0503: "Vehicle Speed Sensor Intermittent/Erratic/High",
  p0505: "Idle Control System Malfunction",
  p0506: "Idle Control System RPM Lower Than Expected",
  p0507: "Idle Control System RPM Higher Than Expected",
  p0510: "Closed Throttle Position Switch Malfunction",
  p0520: "Engine Oil Pressure Sensor/Switch Circuit Malfunction",
  p0521: "Engine Oil Pressure Sensor/Switch Circuit Range/Performance",
  p0522: "Engine Oil Pressure Sensor/Switch Circuit Low Voltage",
  p0523: "Engine Oil Pressure Sensor/Switch Circuit High Voltage",
  p0530: "A/C Refrigerant Pressure Sensor Circuit Malfunction",
  p0531: "A/C Refrigerant Pressure Sensor Circuit Range/Performance",
  p0532: "A/C Refrigerant Pressure Sensor Circuit Low Input",
  p0533: "A/C Refrigerant Pressure Sensor Circuit High Input",
  p0534: "Air Conditioner Refrigerant Charge Loss",
  p0550: "Power Steering Pressure Sensor Circuit Malfunction",
  p0551: "Power Steering Pressure Sensor Circuit Range/Performance",
  p0552: "Power Steering Pressure Sensor Circuit Low Input",
  p0553: "Power Steering Pressure Sensor Circuit High Input",
  p0554: "Power Steering Pressure Sensor Circuit Intermittent",
  p0560: "System Voltage Malfunction",
  p0561: "System Voltage Unstable",
  p0562: "System Voltage Low",
  p0563: "System Voltage High",
  p0565: "Cruise Control On Signal Malfunction",
  p0566: "Cruise Control Off Signal Malfunction",
  p0567: "Cruise Control Resume Signal Malfunction",
  p0568: "Cruise Control Set Signal Malfunction",
  p0569: "Cruise Control Coast Signal Malfunction",
  p0570: "Cruise Control Accel Signal Malfunction",
  p0571: "Cruise Control/Brake Switch A Circuit Malfunction",
  p0572: "Cruise Control/Brake Switch A Circuit Low",
  p0573: "Cruise Control/Brake Switch A Circuit High",
  p0574: "Cruise Control Related Malfunction",
  p0575: "Cruise Control Related Malfunction",
  p0576: "Cruise Control Related Malfunction",
  p0577: "Cruise Control Related Malfunction",
  p0578: "Cruise Control Related Malfunction",
  p0579: "Cruise Control Related Malfunction",
  p0580: "Cruise Control Related Malfunction",
  p0600: "Serial Communication Link Malfunction",
  p0601: "Internal Control Module Memory Check Sum Error",
  p0602: "Control Module Programming Error",
  p0603: "Internal Control Module Keep Alive Memory (KAM) Error",
  p0604: "Internal Control Module Random Access Memory (RAM) Error",
  p0605: "Internal Control Module Read Only Memory (ROM) Error",
  p0606: "PCM Processor Fault",
  p0608: "Control Module VSS Output A Malfunction",
  p0609: "Control Module VSS Output B Malfunction",
  p0620: "Generator Control Circuit Malfunction",
  p0621: "Generator Lamp L Control Circuit Malfunction",
  p0622: "Generator Field F Control Circuit Malfunction",
  p0650: "Malfunction Indicator Lamp (MIL) Control Circuit Malfunction",
  p0654: "Engine RPM Output Circuit Malfunction",
  p0655: "Engine Hot Lamp Output Control Circuit Malfunction",
  p0656: "Fuel Level Output Circuit Malfunction",
  p0700: "Transmission Control System Malfunction",
  p0701: "Transmission Control System Range/Performance",
  p0702: "Transmission Control System Electrical",
  p0703: "Torque Converter/Brake Switch B Circuit Malfunction",
  p0704: "Clutch Switch Input Circuit Malfunction",
  p0705: "Transmission Range Sensor Circuit malfunction (PRNDL Input)",
  p0706: "Transmission Range Sensor Circuit Range/Performance",
  p0707: "Transmission Range Sensor Circuit Low Input",
  p0708: "Transmission Range Sensor Circuit High Input",
  p0709: "Transmission Range Sensor Circuit Intermittent",
  p0710: "Transmission Fluid Temperature Sensor Circuit Malfunction",
  p0711: "Transmission Fluid Temperature Sensor Circuit Range/Performance",
  p0712: "Transmission Fluid Temperature Sensor Circuit Low Input",
  p0713: "Transmission Fluid Temperature Sensor Circuit High Input",
  p0714: "Transmission Fluid Temperature Sensor Circuit Intermittent",
  p0715: "Input/Turbine Speed Sensor Circuit Malfunction",
  p0716: "Input/Turbine Speed Sensor Circuit Range/Performance",
  p0717: "Input/Turbine Speed Sensor Circuit No Signal",
  p0718: "Input/Turbine Speed Sensor Circuit Intermittent",
  p0719: "Torque Converter/Brake Switch B Circuit Low",
  p0720: "Output Speed Sensor Circuit Malfunction",
  p0721: "Output Speed Sensor Range/Performance",
  p0722: "Output Speed Sensor No Signal",
  p0723: "Output Speed Sensor Intermittent",
  p0724: "Torque Converter/Brake Switch B Circuit High",
  p0725: "Engine Speed input Circuit Malfunction",
  p0726: "Engine Speed Input Circuit Range/Performance",
  p0727: "Engine Speed Input Circuit No Signal",
  p0728: "Engine Speed Input Circuit Intermittent",
  p0730: "Incorrect Gear Ratio",
  p0731: "Gear 1 Incorrect ratio",
  p0732: "Gear 2 Incorrect ratio",
  p0733: "Gear 3 Incorrect ratio",
  p0734: "Gear 4 Incorrect ratio",
  p0735: "Gear 5 Incorrect ratio",
  p0736: "Reverse Incorrect ratio",
  p0740: "Torque Converter Clutch Circuit Malfunction",
  p0741: "Torque Converter Clutch Circuit Performance or Stuck Off",
  p0742: "Torque Converter Clutch Circuit Stock On",
  p0743: "Torque Converter Clutch Circuit Electrical",
  p0744: "Torque Converter Clutch Circuit Intermittent",
  p0745: "Pressure Control Solenoid Malfunction",
  p0746: "Pressure Control Solenoid Performance or Stuck Off",
  p0747: "Pressure Control Solenoid Stuck On",
  p0748: "Pressure Control Solenoid Electrical",
  p0749: "Pressure Control Solenoid Intermittent",
  p0750: "Shift Solenoid A Malfunction",
  p0751: "Shift Solenoid A Performance or Stuck Off",
  p0752: "Shift Solenoid A Stuck On",
  p0753: "Shift Solenoid A Electrical",
  p0754: "Shift Solenoid A Intermittent",
  p0755: "Shift Solenoid B Malfunction",
  p0756: "Shift Solenoid B Performance or Stock Off",
  p0757: "Shift Solenoid B Stuck On",
  p0758: "Shift Solenoid B Electrical",
  p0759: "Shift Solenoid B Intermittent",
  p0760: "Shift Solenoid C Malfunction",
  p0761: "Shift Solenoid C Performance or Stuck Off",
  p0762: "Shift Solenoid C Stuck On",
  p0763: "Shift Solenoid C Electrical",
  p0764: "Shift Solenoid C Intermittent",
  p0765: "Shift Solenoid D Malfunction",
  p0766: "Shift Solenoid D Performance or Stuck Off",
  p0767: "Shift Solenoid D Stuck On",
  p0768: "Shift Solenoid D Electrical",
  p0769: "Shift Solenoid D Intermittent",
  p0770: "Shift Solenoid E Malfunction",
  p0771: "Shift Solenoid E Performance or Stuck Off",
  p0772: "Shift Solenoid E Stuck On",
  p0773: "Shift Solenoid E Electrical",
  p0774: "Shift Solenoid E Intermittent",
  p0780: "Shift Malfunction",
  p0781: "1-2 Shift Malfunction",
  p0782: "2-3 Shift Malfunction",
  p0783: "3-4 Shift Malfunction",
  p0784: "4-5 Shift Malfunction",
  p0785: "Shift/Timing Solenoid Malfunction",
  p0786: "Shift/Timing Solenoid Range/Performance",
  p0787: "Shift/Timing Solenoid Low",
  p0788: "Shift/Timing Solenoid High",
  p0789: "Shift/Timing Solenoid Intermittent",
  p0790: "Normal/Performance Switch Circuit Malfunction",
  p0801: "Reverse Inhibit Control Circuit Malfunction",
  p0803: "1-4 Upshift (Skip Shift) Solenoid Control Circuit Malfunction",
  p0804: "1-4 Upshift (Skip Shift) Lamp Control Circuit Malfunction",
  p0805: "Clutch Position Sensor Circuit",
  p0806: "Clutch Position Sensor Circuit Range/Performance",
  p0807: "Clutch Position Sensor Circuit Low",
  p0808: "Clutch Position Sensor Circuit High",
  p0809: "Clutch Position Sensor Circuit Intermittent",
  p0810: "Clutch Position Control Error",
  p0811: "Excessive Clutch Slippage",
  p0812: "Reverse Input Circuit",
  p0813: "Reverse Output Circuit",
  p0814: "Transmission Range Display Circuit",
  p0815: "Upshift Switch Circuit",
  p0816: "Downshift Switch Circuit",
  p0817: "Starter Disable Circuit",
  p0818: "Driveline Disconnect Switch Input Circuit",
  p0819: "Up and Down Shift Switch to Transmission Range Correlation",
  p0820: "Gear Lever X-Y Position Sensor Circuit",
  p0821: "Gear Lever X Position Circuit",
  p0822: "Gear Lever Y Position Circuit",
  p0823: "Gear Lever X Position Circuit Intermittent",
  p0824: "Gear Lever Y Position Circuit Intermittent",
  p0825: "Gear Lever Push-Pull Switch (Shift Anticipate)",
  p0826: "Up and Down Shift Switch Circuit",
  p0827: "Up and Down Shift Switch Circuit Low",
  p0828: "Up and Down Shift Switch Circuit High",
  p0829: "5-6 Shift",
  p0830: "Clutch Pedal Switch A Circuit",
  p0831: "Clutch Pedal Switch A Circuit Low",
  p0832: "Clutch Pedal Switch A Circuit High",
  p0833: "Clutch Pedal Switch B Circuit",
  p0834: "Clutch Pedal Switch B Circuit Low",
  p0835: "Clutch Pedal Switch B Circuit High",
  p0836: "Four Wheel Drive (4WD) Switch Circuit",
  p0837: "Four Wheel Drive (4WD) Switch Circuit Range/Performance",
  p0838: "Four Wheel Drive (4WD) Switch Circuit Low",
  p0839: "Four Wheel Drive (4WD) Switch Circuit High",
  p0840: "Transmission Fluid Pressure Sensor/Switch A Circuit",
  p0841: "Transmission Fluid Pressure Sensor/Switch A Circuit Range/Performance",
  p0842: "Transmission Fluid Pressure Sensor/Switch A Circuit Low",
  p0843: "Transmission Fluid Pressure Sensor/Switch A Circuit High",
  p0844: "Transmission Fluid Pressure Sensor/Switch A Circuit Intermittent",
  p0845: "Transmission Fluid Pressure Sensor/Switch B Circuit",
  p0846: "Transmission Fluid Pressure Sensor/Switch B Circuit Range/Performance",
  p0847: "Transmission Fluid Pressure Sensor/Switch B Circuit Low",
  p0848: "Transmission Fluid Pressure Sensor/Switch B Circuit High",
  p0849: "Transmission Fluid Pressure Sensor/Switch B Circuit Intermittent",
  p0850: "Park/Neutral Switch Input Circuit",
  p0851: "Park/Neutral Switch Input Circuit Low",
  p0852: "Park/Neutral Switch Input Circuit High",
  p0853: "Drive Switch Input Circuit",
  p0854: "Drive Switch Input Circuit Low",
  p0855: "Drive Switch Input Circuit High",
  p0856: "Traction Control Input Signal",
  p0857: "Traction Control Input Signal Range/Performance",
  p0858: "Traction Control Input Signal Low",
  p0859: "Traction Control Input Signal High",
  p0860: "Gear Shift Module Communication Circuit",
  p0861: "Gear Shift Module Communication Circuit Low",
  p0862: "Gear Shift Module Communication Circuit High",
  p0863: "TCM Communication Circuit",
  p0864: "TCM Communication Circuit Range/Performance",
  p0865: "TCM Communication Circuit Low",
  p0866: "TCM Communication Circuit High",
  p0867: "Transmission Fluid Pressure",
  p0868: "Transmission Fluid Pressure Low",
  p0869: "Transmission Fluid Pressure High",
  p0870: "Transmission Fluid Pressure Sensor/Switch C Circuit",
  p0871: "Transmission Fluid Pressure Sensor/Switch C Circuit Range/Performance",
  p0872: "Transmission Fluid Pressure Sensor/Switch C Circuit Low",
  p0873: "Transmission Fluid Pressure Sensor/Switch C Circuit High",
  p0874: "Transmission Fluid Pressure Sensor/Switch C Circuit Intermittent",
  p0875: "Transmission Fluid Pressure Sensor/Switch D Circuit",
  p0876: "Transmission Fluid Pressure Sensor/Switch D Circuit Range/Performance",
  p0877: "Transmission Fluid Pressure Sensor/Switch D Circuit Low",
  p0878: "Transmission Fluid Pressure Sensor/Switch D Circuit High",
  p0879: "Transmission Fluid Pressure Sensor/Switch D Circuit Intermittent",
  p0880: "TCM Power Input Signal",
  p0881: "TCM Power Input Signal Range/Performance",
  p0882: "TCM Power Input Signal Low",
  p0883: "TCM Power Input Signal High",
  p0884: "TCM Power Input Signal Intermittent",
  p0885: "TCM Power Relay Control Circuit/Open",
  p0886: "TCM Power Relay Control Circuit Low",
  p0887: "TCM Power Relay Control Circuit High",
  p0888: "TCM Power Relay Sense Circuit",
  p0889: "TCM Power Relay Sense Circuit Range/Performance",
  p0890: "TCM Power Relay Sense Circuit Low",
  p0891: "TCM Power Relay Sense Circuit High",
  p0892: "TCM Power Relay Sense Circuit Intermittent",
  p0893: "Multiple Gears Engaged",
  p0894: "Transmission Component Slipping",
  p0895: "Shift Time Too Short",
  p0896: "Shift Time Too Long",
  p0897: "Transmission Fluid Deteriorated",
  p0898: "Transmission Control System MIL Request Circuit Low",
  p0899: "Transmission Control System MIL Request Circuit High",
  p2000: "NOx Trap Efficiency Below Threshold Bank 1",
  p2001: "NOx Trap Efficiency Below Threshold Bank 2",
  p2002: "Diesel Particulate Filter Efficiency Below Threshold Bank 1",
  p2003: "Diesel Particulate Filter Efficiency Below Threshold Bank 2",
  p2004: "Intake Manifold Runner Ctrl Stuck Open Bank 1",
  p2005: "Intake Manifold Runner Ctrl Stuck Open Bank 2",
  p2006: "Intake Manifold Runner Ctrl Stuck Closed Bank 1",
  p2007: "Intake Manifold Runner Ctrl Stuck Closed Bank 2",
  p2008: "Intake Manifold Runner Control Circuit Open Bank 1",
  p2009: "Intake Manifold Runner Ctrl Circ Low Bank 1",
  p2010: "Intake Manifold Runner Ctrl Circ High Bank 1",
  p2011: "Intake Manifold Runner Control Circuit Open Bank 2",
  p2012: "Intake Manifold Runner Ctrl Circ Low Bank 2",
  p2013: "Intake Manifold Runner Ctrl Circ High Bank 2",
  p2014: "Intake Manifold Runner Position Sensor/Switch Circ Bank 1",
  p2015: "Intake Manifold Runner Position Sensor/Switch Circ Range/Performance Bank 1",
  p2016: "Intake Manifold Runner Position Sensor/Switch Circ Low Bank 1",
  p2017: "Intake Manifold Runner Position Sensor/Switch Circ High Bank 1",
  p2018: "Intake Manifold Runner Position Sensor/Switch Circ Interm Bank 1",
  p2019: "Intake Manifold Runner Position Sensor/Switch Circ Bank 2",
  p2020: "Intake Manifold Runner Position Sensor/Switch Circ Range/Performance Bank 2",
  p2021: "Intake Manifold Runner Position Sensor/Switch Circ Low Bank 2",
  p2022: "Intake Manifold Runner Position Sensor/Switch Circ High Bank 2",
  p2023: "Intake Manifold Runner Position Sensor/Switch Circ Interm Bank 2",
  p2024: "EVAP Fuel Vapor Temp Sensor Circ",
  p2025: "EVAP Fuel Vapor Temp Sensor Performance",
  p2026: "EVAP Fuel Vapor Temp Sensor Circ Low Voltage",
  p2027: "EVAP Fuel Vapor Temp Sensor Circ High Voltage",
  p2028: "EVAP Fuel Vapor Temp Sensor Circ Interm",
  p2029: "Fuel Fired Heater Disabled",
  p2030: "Fuel Fired Heater Performance",
  p2031: "Exhaust Gas Temp Sensor Circ Bank 1 Sensor 2",
  p2032: "Exhaust Gas Temp Sensor Circ Low Bank 1 Sensor 2",
  p2033: "Exhaust Gas Temp Sensor Circ High Bank 1 Sensor 2",
  p2034: "Exhaust Gas Temp Sensor Circ Bank 2 Sensor 2",
  p2035: "Exhaust Gas Temp Sensor Circ Low Bank 2 Sensor 2",
  p2036: "Exhaust Gas Temp Sensor Circ High Bank 2 Sensor 2",
  p2037: "Reductant Inj Air Press Sensor Circ",
  p2038: "Reductant Inj Air Press Sensor Circ Range/Performance",
  p2039: "Reductant Inj Air Press Sensor Circ Low Input",
  p2040: "Reductant Inj Air Press Sensor Circ High Input",
  p2041: "Reductant Inj Air Press Sensor Circ Interm",
  p2042: "Reductant Temp Sensor Circ",
  p2043: "Reductant Temp Sensor Circ Range/Performance",
  p2044: "Reductant Temp Sensor Circ Low Input",
  p2045: "Reductant Temp Sensor Circ High Input",
  p2046: "Reductant Temp Sensor Circ Interm",
  p2047: "Reductant Injector Circ/Open Bank 1 Unit 1",
  p2048: "Reductant Injector Circ Low Bank 1 Unit 1",
  p2049: "Reductant Injector Circ High Bank 1 Unit 1",
  p2050: "Reductant Injector Circ/Open Bank 2 Unit 1",
  p2051: "Reductant Injector Circ Low Bank 2 Unit 1",
  p2052: "Reductant Injector Circ High Bank 2 Unit 1",
  p2053: "Reductant Injector Circ/Open Bank 1 Unit 2",
  p2054: "Reductant Injector Circ Low Bank 1 Unit 2",
  p2055: "Reductant Injector Circ High Bank 1 Unit 2",
  p2056: "Reductant Injector Circ/Open Bank 2 Unit 2",
  p2057: "Reductant Injector Circ Low Bank 2 Unit 2",
  p2058: "Reductant Injector Circ High Bank 2 Unit 2",
  p2059: "Reductant Inj Air Pump Ctrl Circ/Open",
  p2060: "Reductant Inj Air Pump Ctrl Circ Low",
  p2061: "Reductant Inj Air Pump Ctrl Circ High",
  p2062: "Reductant Supply Ctrl Circ/Open",
  p2063: "Reductant Supply Ctrl Circ Low",
  p2064: "Reductant Supply Ctrl Circ High",
  p2065: "Fuel Level SensorB Circ",
  p2066: "Fuel Level SensorB Performance",
  p2067: "Fuel Level SensorB Circ Low",
  p2068: "Fuel Level SensorB Circ High",
  p2069: "Fuel Level SensorB Circ Interm",
  p2070: "Intake Manifold Tuning (IMT) Valve Stuck Open",
  p2071: "IMT Valve Stuck Closed",
  p2072: "Throttle Actuator Control System - Ice Blockage",
  p2073: "Manifold Absolute Pressure/Mass Air Flow - Throttle Position Correlation at Idle",
  p2074: "Manifold Absolute Pressure/Mass Air Flow - Throttle Position Correlation at Higher Load",
  p2075: "IMT Valve Position Sensor/Switch Circ",
  p2076: "IMT Valve Position Sensor/Switch Circ Range/Performance",
  p2077: "IMT Valve Position Sensor/Switch Circ Low",
  p2078: "IMT Valve Position Sensor/Switch Circ High",
  p2079: "IMT Valve Position Sensor/Switch Circ Interm",
  p2080: "Exhaust Gas Temp Sensor Circ Range/Performance Bank 1 Sensor 1",
  p2081: "Exhaust Gas Temp Sensor Circ Interm Bank 1 Sensor 1",
  p2082: "Exhaust Gas Temp Sensor Circ Range/Performance Bank 2 Sensor 1",
  p2083: "Exhaust Gas Temp Sensor Circ Interm Bank 2 Sensor 1",
  p2084: "Exhaust Gas Temp Sensor Circ Range/Performance Bank 1 Sensor 2",
  p2085: "Exhaust Gas Temp Sensor Circ Interm Bank 1 Sensor 2",
  p2086: "Exhaust Gas Temp Sensor Circ Range/Performance Bank 2 Sensor 2",
  p2087: "Exhaust Gas Temp Sensor Circ Interm Bank 2 Sensor 2",
  p2088: "A Camshaft Position Actuator Ctrl Circ Low Bank 1",
  p2089: "A Camshaft Position Actuator Ctrl Circ High Bank 1",
  p2090: "B Camshaft Position Actuator Ctrl Circ Low Bank 1",
  p2091: "B Camshaft Position Actuator Ctrl Circ High Bank 1",
  p2092: "A Camshaft Position Actuator Ctrl Circ Low Bank 2",
  p2093: "A Camshaft Position Actuator Ctrl Circ High Bank 2",
  p2094: "B Camshaft Position Actuator Ctrl Circ Low Bank 2",
  p2095: "B Camshaft Position Actuator Ctrl Circ High Bank 2",
  p2096: "Post Catalyst Fuel Trim System Too Lean Bank 1",
  p2097: "Post Catalyst Fuel Trim System Too Rich Bank 1",
  p2098: "Post Catalyst Fuel Trim System Too Lean Bank 2",
  p2099: "Post Catalyst Fuel Trim System Too Rich Bank 2",
  p2100: "Throttle Actuator Ctrl Motor Circ/Open",
  p2101: "Throttle Actuator Ctrl Motor Circ Range/Performance",
  p2102: "Throttle Actuator Ctrl Motor Circ Low",
  p2103: "Throttle Actuator Ctrl Motor Circ High",
  p2104: "Throttle Actuator Ctrl Sys-Forced Idle",
  p2105: "Throttle Actuator Ctrl Sys-Forced Engine Shutdown",
  p2106: "Throttle Actuator Ctrl Sys-Forced Limited Power",
  p2107: "Throttle Actuator Ctrl Mod Processor",
  p2108: "Throttle Actuator Ctrl Mod Performance",
  p2109: "Throttle/Pedal Position SensorA Minimum Stop Performance",
  p2110: "Throttle Actuator Ctrl Sys-Forced Limited RPM",
  p2111: "Throttle Actuator Ctrl Sys-Stuck Open",
  p2112: "Throttle Actuator Ctrl Sys-Stuck Closed",
  p2113: "Throttle/Pedal Position SensorB Minimum Stop Performance",
  p2114: "Throttle/Pedal Position Sensor C Minimum Stop Performance",
  p2115: "Throttle/Pedal Position Sensor D Minimum Stop Performance",
  p2116: "Throttle/Pedal Position Sensor E Minimum Stop Performance",
  p2117: "Throttle/Pedal Position Sensor F Minimum Stop Performance",
  p2118: "Throttle Actuator Ctrl Motor Current Range/Performance",
  p2119: "Throttle Actuator Ctrl Throttle Body Range/Performance",
  p2120: "Throttle/Pedal Position Sensor/Switch D Circ",
  p2121: "Throttle/Pedal Position Sensor/Switch D Circ Range/Performance",
  p2122: "Throttle/Pedal Position Sensor/Switch D Circ Low Input",
  p2123: "Throttle/Pedal Position Sensor/Switch D Circ High Input",
  p2124: "Throttle/Pedal Position Sensor/Switch D Circ Interm",
  p2125: "Throttle/Pedal Position Sensor/Switch E Circ",
  p2126: "Throttle/Pedal Position Sensor/Switch E Circ Range/Performance",
  p2127: "Throttle/Pedal Position Sensor/Switch E Circ Low Input",
  p2128: "Throttle/Pedal Position Sensor/Switch E Circ High Input",
  p2129: "Throttle/Pedal Position Sensor/Switch E Circ Interm",
  p2130: "Throttle/Pedal Position Sensor/Switch F Circ",
  p2131: "Throttle/Pedal Position Sensor/Switch F Circ Range Performance",
  p2132: "Throttle/Pedal Position Sensor/Switch F Circ Low Input",
  p2133: "Throttle/Pedal Position Sensor/Switch F Circ High Input",
  p2134: "Throttle/Pedal Position Sensor/Switch F Circ Interm",
  p2135: "Throttle/Pedal Position Sensor/Switch A / B Voltage Correlation",
  p2136: "Throttle/Pedal Position Sensor/Switch A / C Voltage Correlation",
  p2137: "Throttle/Pedal Position Sensor/Switch B / C Voltage Correlation",
  p2138: "Throttle/Pedal Position Sensor/Switch D / E Voltage Correlation",
  p2139: "Throttle/Pedal Position Sensor/Switch D / F Voltage Correlation",
  p2140: "Throttle/Pedal Position Sensor/Switch E / F Voltage Correlation",
  p2141: "Exhaust Gas Recirculation Throttle Ctrl Circ Low",
  p2142: "Exhaust Gas Recirculation Throttle Ctrl Circ High",
  p2143: "Exhaust Gas Recirculation Vent Ctrl Circ/Open",
  p2144: "Exhaust Gas Recirculation Vent Ctrl Circ Low",
  p2145: "Exhaust Gas Recirculation Vent Ctrl Circ High",
  p2146: "Fuel Injector Group A Supply Voltage Circ/Open",
  p2147: "Fuel Injector Group A Supply Voltage Circ Low",
  p2148: "Fuel Injector Group A Supply Voltage Circ High",
  p2149: "Fuel Injector Group B Supply Voltage Circ/Open",
  p2150: "Fuel Injector Group B Supply Voltage Circ Low",
  p2151: "Fuel Injector Group B Supply Voltage Circ High",
  p2152: "Fuel Injector Group C Supply Voltage Circ/Open",
  p2153: "Fuel Injector Group C Supply Voltage Circ Low",
  p2154: "Fuel Injector Group C Supply Voltage Circ High",
  p2155: "Fuel Injector Group D Supply Voltage Circ/Open",
  p2156: "Fuel Injector Group D Supply Voltage Circ Low",
  p2157: "Fuel Injector Group D Supply Voltage Circ High",
  p2158: "Vehicle Speed Sensor B",
  p2159: "Vehicle Speed Sensor B Range/Performance",
  p2160: "Vehicle Speed Sensor B Circ Low",
  p2161: "Vehicle Speed Sensor B Interm/Erratic",
  p2162: "Vehicle Speed Sensor A / B Correlation",
  p2163: "Throttle/Pedal Position Sensor A Maximum Stop Performance",
  p2164: "Throttle/Pedal Position Sensor B Maximum Stop Performance",
  p2165: "Throttle/Pedal Position Sensor C Maximum Stop Performance",
  p2166: "Throttle/Pedal Position Sensor D Maximum Stop Performance",
  p2167: "Throttle/Pedal Position Sensor E Maximum Stop Performance",
  p2168: "Throttle/Pedal Position Sensor F Maximum Stop Performance",
  p2169: "Exhaust Press Reg Vent Solenoid Ctrl Circ/Open",
  p2170: "Exhaust Press Reg Vent Solenoid Ctrl Circ Low",
  p2171: "Exhaust Press Reg Vent Solenoid Ctrl Circ High",
  p2172: "Throttle Actuator Ctrl Sys-Sudden High Airflow Detected",
  p2173: "Throttle Actuator Ctrl Sys-High Airflow Detected",
  p2174: "Throttle Actuator Ctrl Sys-Sudden Low Airflow Detected",
  p2175: "Throttle Actuator Ctrl Sys-Low Airflow Detected",
  p2176: "Throttle Actuator Ctrl Sys-Idle Position Not Learned",
  p2177: "Sys Too Lean Off Idle Bank 1",
  p2178: "Sys Too Rich Off Idle Bank 1",
  p2179: "Sys Too Lean Off Idle Bank 2",
  p2180: "Sys Too Rich Off Idle Bank 2",
  p2181: "Cooling System Performance",
  p2182: "Engine Coolant Temp Sensor 2 Circ",
  p2183: "Engine Coolant Temp Sensor 2 Circ Range/Performance",
  p2184: "Engine Coolant Temp Sensor 2 Circ Low",
  p2185: "Engine Coolant Temp Sensor 2 Circ High",
  p2186: "Engine Coolant Temp Sensor 2 Circ Interm/Erratic",
  p2187: "Sys Too Lean at Idle Bank 1",
  p2188: "Sys Too Rich at Idle Bank 1",
  p2189: "Sys Too Lean at Idle Bank 2",
  p2190: "Sys Too Rich at Idle Bank 2",
  p2191: "Sys Too Lean at Higher Load Bank 1",
  p2192: "Sys Too Rich at Higher Load Bank 1",
  p2193: "Sys Too Lean at Higher Load Bank 2",
  p2194: "Sys Too Rich at Higher Load Bank 2",
  p2195: "O2 Sensor Signal Stuck Lean Bank 1 Sensor 1",
  p2196: "O2 Sensor Signal Stuck Rich Bank 1 Sensor 1",
  p2197: "O2 Sensor Signal Stuck Lean Bank 2 Sensor 1",
  p2198: "O2 Sensor Signal Stuck Rich Bank 2 Sensor 1",
  p2199: "Intake Air Temp Sensor 1 / 2 Correlation",
  p2200: "NOx Sensor Circ Bank 1",
  p2201: "NOx Sensor Circ Range/Performance Bank 1",
  p2202: "NOx Sensor Circ Low Input Bank 1",
  p2203: "NOx Sensor Circ High Input Bank 1",
  p2204: "NOx Sensor Circ Interm Input Bank 1",
  p2205: "NOx Sensor Heater Ctrl Circ/Open Bank 1",
  p2206: "NOx Sensor Heater Ctrl Circ Low Bank 1",
  p2207: "NOx Sensor Heater Ctrl Circ High Bank 1",
  p2208: "NOx Sensor Heater Sense Circ Bank 1",
  p2209: "NOx Sensor Heater Sense Circ Range/Performance Bank 1",
  p2210: "NOx Sensor Heater Sense Circ Low Input Bank 1",
  p2211: "NOx Sensor Heater Sense Circ High Input Bank 1",
  p2212: "NOx Sensor Heater Sense Circ Interm Bank 1",
  p2213: "NOx Sensor Circ Bank 2",
  p2214: "NOx Sensor Circ Range/Performance Bank 2",
  p2215: "NOx Sensor Circ Low Input Bank 2",
  p2216: "NOx Sensor Circ High Input Bank 2",
  p2217: "NOx Sensor Circ Interm Input Bank 2",
  p2218: "NOx Sensor Heater Ctrl Circ/Open Bank 2",
  p2219: "NOx Sensor Heater Ctrl Circ Low Bank 2",
  p2220: "NOx Sensor Heater Ctrl Circ High Bank 2",
  p2221: "NOx Sensor Heater Sense Circ Bank 2",
  p2222: "NOx Sensor Heater Sense Circ Range/Performance Bank 2",
  p2223: "NOx Sensor Heater Sense Circ Low Bank 2",
  p2224: "NOx Sensor Heater Sense Circ High Bank 2",
  p2225: "NOx Sensor Heater Sense Circ Interm Bank 2",
  p2226: "Barometric Press Circ",
  p2227: "Barometric Press Circ Range/Performance",
  p2228: "Barometric Press Circ Low",
  p2229: "Barometric Press Circ High",
  p2230: "Barometric Press Circ Interm",
  p2231: "O2 Sensor Signal Circ Shorted to Heater Circ Bank 1 Sensor 1",
  p2232: "O2 Sensor Signal Circ Shorted to Heater Circ Bank 1 Sensor 2",
  p2233: "O2 Sensor Signal Circ Shorted to Heater Circ Bank 1 Sensor 3",
  p2234: "O2 Sensor Signal Circ Shorted to Heater Circ Bank 2 Sensor 1",
  p2235: "O2 Sensor Signal Circ Shorted to Heater Circ Bank 2 Sensor 2",
  p2236: "O2 Sensor Signal Circ Shorted to Heater Circ Bank 2 Sensor 3",
  p2237: "O2 Sensor Positive Current Ctrl Circ/Open Bank 1 Sensor 1",
  p2238: "O2 Sensor Positive Current Ctrl Circ Low Bank 1 Sensor 1",
  p2239: "O2 Sensor Positive Current Ctrl Circ High Bank 1 Sensor 1",
  p2240: "O2 Sensor Positive Current Ctrl Circ/Open Bank 2 Sensor 1",
  p2241: "O2 Sensor Positive Current Ctrl Circ Low Bank 2 Sensor 1",
  p2242: "O2 Sensor Positive Current Ctrl Circ High Bank 2 Sensor 1",
  p2243: "O2 Sensor Ref Voltage Circ/Open Bank 1 Sensor 1",
  p2244: "O2 Sensor Ref Voltage Performance Bank 1 Sensor 1",
  p2245: "O2 Sensor Ref Voltage Circ Low Bank 1 Sensor 1",
  p2246: "O2 Sensor Ref Voltage Circ High Bank 1 Sensor 1",
  p2247: "O2 Sensor Ref Voltage Circ/Open Bank 2 Sensor 1",
  p2248: "O2 Sensor Ref Voltage Performance Bank 2 Sensor 1",
  p2249: "O2 Sensor Ref Voltage Circ Low Bank 2 Sensor 1",
  p2250: "O2 Sensor Ref Voltage Circ High Bank 2 Sensor 1",
  p2251: "O2 Sensor Negative Current Ctrl Circ/Open Bank 1 Sensor 1",
  p2252: "O2 Sensor Negative Current Ctrl Circ Low Bank 1 Sensor 1",
  p2253: "O2 Sensor Negative Current Ctrl Circ High Bank 1 Sensor 1",
  p2254: "O2 Sensor Negative Current Ctrl Circ/Open Bank 2 Sensor 1",
  p2255: "O2 Sensor Negative Current Ctrl Circ Low Bank 2 Sensor 1",
  p2256: "O2 Sensor Negative Current Ctrl Circ High Bank 2 Sensor 1",
  p2257: "Sec Air Inj Sys Ctrl A Circ Low",
  p2258: "Sec Air Inj Sys Ctrl A Circ High",
  p2259: "Sec Air Inj Sys Ctrl B Circ Low",
  p2260: "Sec Air Inj Sys Ctrl B Circ High",
  p2261: "T/S Charger Bypass Valve-Mechanical",
  p2262: "Turbo Boost Press Not Detected-Mechanical",
  p2263: "Turbo/Supercharger Boost System Performance",
  p2264: "Water in Fuel Sensor Circ",
  p2265: "Water in Fuel Sensor Circ Range/Performance",
  p2266: "Water in Fuel Sensor Circ Low",
  p2267: "Water in Fuel Sensor Circ High",
  p2268: "Water in Fuel Sensor Circ Interm",
  p2269: "Water in Fuel Condition",
  p2270: "O2 Sensor Signal Stuck Lean Bank 1 Sensor 2",
  p2271: "O2 Sensor Signal Stuck Rich Bank 1 Sensor 2",
  p2272: "O2 Sensor Signal Stuck Lean Bank 2 Sensor 2",
  p2273: "O2 Sensor Signal Stuck Rich Bank 2 Sensor 2",
  p2274: "O2 Sensor Signal Stuck Lean Bank 1 Sensor 3",
  p2275: "O2 Sensor Signal Stuck Rich Bank 1 Sensor 3",
  p2276: "O2 Sensor Signal Stuck Lean Bank 2 Sensor 3",
  p2277: "O2 Sensor Signal Stuck Rich Bank 2 Sensor 3",
  p2278: "O2 Sensor Signals Swapped Bank 1 Sensor 3 / Bank 2 Sensor 3",
  p2279: "Intake Air Sys Leak",
  p2280: "Air Flow Restriction / Air Leak Between Air Filter and MAF",
  p2281: "Air Leak Between MAF and Throttle Body",
  p2282: "Air Leak Between Throttle Body and Intake Valves",
  p2283: "Injector Ctrl Press Sensor Circ",
  p2284: "Injector Ctrl Press Sensor Circ Range/Performance",
  p2285: "Injector Ctrl Press Sensor Circ Low",
  p2286: "Injector Ctrl Press Sensor Circ High",
  p2287: "Injector Ctrl Press Sensor Circ Interm",
  p2288: "Injector Ctrl Press Too High",
  p2289: "Injector Ctrl Press Too High-Engine Off",
  p2290: "Injector Ctrl Press Too Low",
  p2291: "Injector Ctrl Press Too Low-Engine Cranking",
  p2292: "Injector Ctrl Press Erratic",
  p2293: "Fuel Press Reg 2 Performance",
  p2294: "Fuel Press Reg 2 Ctrl Circ",
  p2295: "Fuel Press Reg 2 Ctrl Circ Low",
  p2296: "Fuel Press Reg 2 Ctrl Circ High",
  p2297: "O2 Sensor Out of Range During Deceleration Bank 1 Sensor 1",
  p2298: "O2 Sensor Out of Range During Deceleration Bank 2 Sensor 1",
  p2299: "Brake Pedal Position / Accelerator Pedal Position Incompatible",
  p2300: "Ignition Coil A Pri Ctrl Circ Low",
  p2301: "Ignition Coil A Pri Ctrl Circ High",
  p2302: "Ignition Coil A Sec Circ",
  p2303: "Ignition Coil B Pri Ctrl Circ Low",
  p2304: "Ignition Coil B Pri Ctrl Circ High",
  p2305: "Ignition Coil B Sec Circ",
  p2306: "Ignition Coil C Pri Ctrl Circ Low",
  p2307: "Ignition Coil C Pri Ctrl Circ High",
  p2308: "Ignition Coil C Sec Circ",
  p2309: "Ignition Coil D Pri Ctrl Circ Low",
  p2310: "Ignition Coil D Pri Ctrl Circ High",
  p2311: "Ignition Coil D Sec Circ",
  p2312: "Ignition Coil E Pri Ctrl Circ Low",
  p2313: "Ignition Coil E Pri Ctrl Circ High",
  p2314: "Ignition Coil E Sec Circ",
  p2315: "Ignition Coil F Pri Ctrl Circ Low",
  p2316: "Ignition Coil F Pri Ctrl Circ High",
  p2317: "Ignition Coil F Sec Circ",
  p2318: "Ignition Coil G Pri Ctrl Circ Low",
  p2319: "Ignition Coil G Pri Ctrl Circ High",
  p2320: "Ignition Coil G Sec Circ",
  p2321: "Ignition Coil H Pri Ctrl Circ Low",
  p2322: "Ignition Coil H Pri Ctrl Circ High",
  p2323: "Ignition Coil H Sec Circ",
  p2324: "Ignition Coil I Pri Ctrl Circ Low",
  p2325: "Ignition Coil I Pri Ctrl Circ High",
  p2326: "Ignition Coil I Sec Circ",
  p2327: "Ignition Coil J Pri Ctrl Circ Low",
  p2328: "Ignition Coil J Pri Ctrl Circ High",
  p2329: "Ignition Coil J Sec Circ",
  p2330: "Ignition Coil K Pri Ctrl Circ Low",
  p2331: "Ignition Coil K Pri Ctrl Circ High",
  p2332: "Ignition Coil K Sec Circ",
  p2333: "Ignition Coil L Pri Ctrl Circ Low",
  p2334: "Ignition Coil L Pri Ctrl Circ High",
  p2335: "Ignition Coil L Sec Circ",
  p2336: "Cylinder #1 Above Knock Threshold",
  p2337: "Cylinder #2 Above Knock Threshold",
  p2338: "Cylinder #3 Above Knock Threshold",
  p2339: "Cylinder #4 Above Knock Threshold",
  p2340: "Cylinder #5 Above Knock Threshold",
  p2341: "Cylinder #6 Above Knock Threshold",
  p2342: "Cylinder #7 Above Knock Threshold",
  p2343: "Cylinder #8 Above Knock Threshold",
  p2344: "Cylinder #9 Above Knock Threshold",
  p2345: "Cylinder #10 Above Knock Threshold",
  p2346: "Cylinder #11 Above Knock Threshold",
  p2347: "Cylinder #12 Above Knock Threshold",
  p2400: "EVAP Leak Detection Pump Ctrl Circ/Open",
  p2401: "EVAP Leak Detection Pump Ctrl Circ Low",
  p2402: "EVAP Leak Detection Pump Ctrl Circ High",
  p2403: "EVAP Leak Detection Pump Sense Circ/Open",
  p2404: "EVAP Leak Detection Pump Sense Circ Range/Performance",
  p2405: "EVAP Leak Detection Pump Sense Circ Low",
  p2406: "EVAP Leak Detection Pump Sense Circ High",
  p2407: "EVAP Leak Detection Pump Sense Circ Interm/Erratic",
  p2408: "Fuel Cap Sensor/Switch Circ",
  p2409: "Fuel Cap Sensor/Switch Circ Range/Performance",
  p2410: "Fuel Cap Sensor/Switch Circ Low",
  p2411: "Fuel Cap Sensor/Switch Circ High",
  p2412: "Fuel Cap Sensor/Switch Circ Interm/Erratic",
  p2413: "Exhaust Gas Recirculation Sys Performance",
  p2414: "O2 Sensor Exhaust Sample Error Bank 1 Sensor 1",
  p2415: "O2 Sensor Exhaust Sample Error Bank 2 Sensor 1",
  p2416: "O2 Sensor Signals Swapped Bank 1 Sensor 2 / Bank 1 Sensor 3",
  p2417: "O2 Sensor Signals Swapped Bank 2 Sensor 2 / Bank 2 Sensor 3",
  p2418: "EVAP Switching Valve Ctrl Circ /Open",
  p2419: "EVAP Switching Valve Ctrl Circ Low",
  p2420: "EVAP Switching Valve Ctrl Circ High",
  p2421: "EVAP Vent Valve Stuck Open",
  p2422: "EVAP Vent Valve Stuck Closed",
  p2423: "HC Adsorption Catalyst Efficiency Below Threshold Bank 1",
  p2424: "HC Adsorption Catalyst Efficiency Below Threshold Bank 2",
  p2425: "Exhaust Gas Recirculation Cooling Valve Ctrl Circ/Open",
  p2426: "Exhaust Gas Recirculation Cooling Valve Ctrl Circ Low",
  p2427: "Exhaust Gas Recirculation Cooling Valve Ctrl Circ High",
  p2428: "Exhaust Gas Temp Too High Bank 1",
  p2429: "Exhaust Gas Temp Too High Bank 2",
  p2430: "Sec Air Inj Sys Air Flow/Press Sensor Circ Bank 1",
  p2431: "Sec Air Inj Sys Air Flow/Press Sensor Circ Range/Performance Bank 1",
  p2432: "Sec Air Inj Sys Air Flow/Press Sensor Circ Low Bank 1",
  p2433: "Sec Air Inj Sys Air Flow/Press Sensor Circ High Bank 1",
  p2434: "Sec Air Inj Sys Air Flow/Press Sensor Circ Interm/Erratic Bank 1",
  p2435: "Sec Air Inj Sys Air Flow/Press Sensor Circ Bank 2",
  p2436: "Sec Air Inj Sys Air Flow/Press Sensor Circ Range/Performance Bank 2",
  p2437: "Sec Air Inj Sys Air Flow/Press Sensor Circ Low Bank 2",
  p2438: "Sec Air Inj Sys Air Flow/Press Sensor Circ High Bank 2",
  p2439: "Sec Air Inj Sys Air Flow/Press Sensor Circ Interm/Eratic Bank 2",
  p2440: "Sec Air Inj Sys Switching Valve Stuck Open Bank 1",
  p2441: "Sec Air Inj Sys Switching Valve Stuck Closed Bank 1",
  p2442: "Sec Air Inj Sys Switching Valve Stuck Open Bank 2",
  p2443: "Sec Air Inj Sys Switching Valve Stuck Closed Bank 2",
  p2444: "Sec Air Inj Sys Pump Stuck On Bank 1",
  p2445: "Sec Air Inj Sys Pump Stuck Off Bank 1",
  p2446: "Sec Air Inj Sys Pump Stuck On Bank 2",
  p2447: "Sec Air Inj Sys Pump Stuck Off Bank 2",
  p2453: "Particulate Matter Trap Differential Pressure Sensor Signal Performance",
  p2455: "DPF Differential Pressure Sensor Short to Voltage",
  p2500: "Generator Lamp/L-Terminal Circ Low",
  p2501: "Generator Lamp/L-Terminal Circ High",
  p2502: "Charging Sys Voltage",
  p2503: "Charging Sys Voltage Low",
  p2504: "Charging Sys Voltage High",
  p2505: "ECM/PCM Power Input Signal",
  p2506: "ECM/PCM Power Input Signal Range/Performance",
  p2507: "ECM/PCM Power Input Signal Low",
  p2508: "ECM/PCM Power Input Signal High",
  p2509: "ECM/PCM Power Input Signal Intermittent",
  p2510: "ECM/PCM Power Relay Sense Circ Range/Performance",
  p2511: "ECM/PCM Power Relay Sense Circ Interm",
  p2512: "Event Data Recorder Request Circ/ Open",
  p2513: "Event Data Recorder Request Circ Low",
  p2514: "Event Data Recorder Request Circ High",
  p2515: "A/C Refrigerant Press SensorB Circ",
  p2516: "A/C Refrigerant Press SensorB Circ Range/Performance",
  p2517: "A/C Refrigerant Press SensorB Circ Low",
  p2518: "A/C Refrigerant Press SensorB Circ High",
  p2519: "A/C Request A Circ",
  p2520: "A/C Request A Circ Low",
  p2521: "A/C Request A Circ High",
  p2522: "A/C Request B Circ",
  p2523: "A/C Request B Circ Low",
  p2524: "A/C Request B Circ High",
  p2525: "Vacuum Reservoir Press Sensor Circ",
  p2526: "Vacuum Reservoir Press Sensor Circ Range/Performance",
  p2527: "Vacuum Reservoir Press Sensor Circ Low",
  p2528: "Vacuum Reservoir Press Sensor Circ High",
  p2529: "Vacuum Reservoir Press Sensor Circ Interm",
  p2530: "Ignition Switch Run Position Circ",
  p2531: "Ignition Switch Run Position Circ Low",
  p2532: "Ignition Switch Run Position Circ High",
  p2533: "Ignition Switch Run/Start Position Circ",
  p2534: "Ignition Switch Run/Start Position Circ Low",
  p2535: "Ignition Switch Run/Start Position Circ High",
  p2536: "Ignition Switch Accessory Position Circ",
  p2537: "Ignition Switch Accessory Position Circ Low",
  p2538: "Ignition Switch Accessory Position Circ High",
  p2539: "Low Press Fuel Sys Sensor Circ",
  p2540: "Low Press Fuel Sys Sensor Circ Range/Performance",
  p2541: "Low Press Fuel Sys Sensor Circ Low",
  p2542: "Low Press Fuel Sys Sensor Circ High",
  p2543: "Low Press Fuel Sys Sensor Circ Interm",
  p2544: "Torque Mgmt Request Input Signal A",
  p2545: "Torque Mgmt Request Input Signal A Range/Performance",
  p2546: "Torque Mgmt Request Input Signal A Low",
  p2547: "Torque Mgmt Request Input Signal A High",
  p2548: "Torque Mgmt Request Input Signal B",
  p2549: "Torque Mgmt Request Input Signal B Range/Performance",
  p2550: "Torque Mgmt Request Input Signal B Low",
  p2551: "Torque Mgmt Request Input Signal B High",
  p2552: "Throttle/Fuel Inhibit Circ",
  p2553: "Throttle/Fuel Inhibit Circ Range/Performance",
  p2554: "Throttle/Fuel Inhibit Circ Low",
  p2555: "Throttle/Fuel Inhibit Circ High",
  p2556: "Engine Coolant Level Sensor/Switch Circ",
  p2557: "Engine Coolant Level Sensor/Switch Circ Range/Performance",
  p2558: "Engine Coolant Level Sensor/Switch Circ Low",
  p2559: "Engine Coolant Level Sensor/Switch Circ High",
  p2560: "Engine Coolant Level Low",
  p2561: "A/C Ctrl Mod Requested MIL Illumination",
  p2562: "Turbocharger Boost Ctrl Position Sensor Circ",
  p2563: "Turbocharger Boost Ctrl Position Sensor Circ Range/Performance",
  p2564: "Turbocharger Boost Ctrl Position Sensor Circ Low",
  p2565: "Turbocharger Boost Ctrl Position Sensor Circ High",
  p2566: "Turbocharger Boost Ctrl Position Sensor Circ Interm",
  p2567: "Direct Ozone Reduction Catalyst Temp Sensor Circ",
  p2568: "Direct Ozone Reduction Catalyst Temp Sensor Circ Range/Performance",
  p2569: "Direct Ozone Reduction Catalyst Temp Sensor Circ Low",
  p2570: "Direct Ozone Reduction Catalyst Temp Sensor Circ High",
  p2571: "Direct Ozone Reduction Catalyst Temp Sensor Circ Interm/Erratic4",
  p2572: "Direct Ozone Reduction Catalyst Deterioration Sensor Circ4",
  p2573: "Direct Ozone Reduction Catalyst Deterioration Sensor Circ Range/Perf4",
  p2574: "Direct Ozone Reduction Catalyst Deterioration Sensor Circ Low4",
  p2575: "Direct Ozone Reduction Catalyst Deterioration Sensor Circ High4",
  p2576: "Direct Ozone Reduction Catalyst Deterioration Sensor Circ Interm/Erratic",
  p2577: "Direct Ozone Reduction Catalyst Efficiency Below Threshold",
  p2600: "Coolant Pump Ctrl Circ/Open",
  p2601: "Coolant Pump Ctrl Circ Range/Performance",
  p2602: "Coolant Pump Ctrl Circ Low",
  p2603: "Coolant Pump Ctrl Circ High",
  p2604: "Intake Air Heater A Circ Range/Performance",
  p2605: "Intake Air Heater A Circ/Open",
  p2606: "Intake Air Heater B Circ Range/Performance",
  p2607: "Intake Air Heater B Circ Low",
  p2608: "Intake Air Heater B Circ High",
  p2609: "Intake Air Heater Sys Performance",
  p2610: "ECM/PCM Internal Engine Off Timer Performance",
  p2611: "A/C Refrigerant Distribution Valve Ctrl Circ/Open",
  p2612: "A/C Refrigerant Distribution Valve Ctrl Circ Low",
  p2613: "A/C Refrigerant Distribution Valve Ctrl Circ High",
  p2614: "Camshaft Position Signal Output Circ/Open",
  p2615: "Camshaft Position Signal Output Circ Low",
  p2616: "Camshaft Position Signal Output Circ High",
  p2617: "Crank Position Signal Output Circ/Open",
  p2618: "Crank Position Signal Output Circ Low",
  p2619: "Crank Position Signal Output Circ High",
  p2620: "Throttle Position Output Circ/Open",
  p2621: "Throttle Position Output Circ Low",
  p2622: "Throttle Position Output Circ High",
  p2623: "Injector Ctrl Press Reg Circ/Open",
  p2624: "Injector Ctrl Press Reg Circ Low",
  p2625: "Injector Ctrl Press Reg Circ High",
  p2626: "O2 Sensor Pumping Current Trim Circ/Open Bank 1 Sensor 1",
  p2627: "O2 Sensor Pumping Current Trim Circ Low Bank 1 Sensor 1",
  p2628: "O2 Sensor Pumping Current Trim Circ High Bank 1 Sensor 1",
  p2629: "O2 Sensor Pumping Current Trim Circ/Open Bank 2 Sensor 1",
  p2630: "O2 Sensor Pumping Current Trim Circ Low Bank 2 Sensor 1",
  p2631: "O2 Sensor Pumping Current Trim Circ High Bank 2 Sensor 1",
  p2632: "Fuel Pump B Ctrl Circ /Open",
  p2633: "Fuel Pump B Ctrl Circ Low",
  p2634: "Fuel Pump B Ctrl Circ High",
  p2635: "Fuel Pump A Low Flow / Performance",
  p2636: "Fuel Pump B Low Flow / Performance",
  p2637: "Torque Mgmt Feedback Signal A",
  p2638: "Torque Mgmt Feedback Signal A Range/Performance",
  p2639: "Torque Mgmt Feedback Signal A Low",
  p2640: "Torque Mgmt Feedback Signal A High",
  p2641: "Torque Mgmt Feedback Signal B",
  p2642: "Torque Mgmt Feedback Signal B Range/Performance",
  p2643: "Torque Mgmt Feedback Signal B Low",
  p2644: "Torque Mgmt Feedback Signal B High",
  p2645: "A Rocker Arm Actuator Ctrl Circ/Open Bank 1",
  p2646: "A Rocker Arm Actuator Sys Performance or Stuck Off Bank 1",
  p2647: "A Rocker Arm Actuator Sys Stuck On Bank 1",
  p2648: "A Rocker Arm Actuator Ctrl Circ Low Bank 1",
  p2649: "A Rocker Arm Actuator Ctrl Circ High Bank 1",
  p2650: "B Rocker Arm Actuator Ctrl Circ/Open Bank 1",
  p2651: "B Rocker Arm Actuator Sys Performance or Stuck Off Bank 1",
  p2652: "B Rocker Arm Actuator Sys Stuck On Bank 1",
  p2653: "B Rocker Arm Actuator Ctrl Circ Low Bank 1",
  p2654: "B Rocker Arm Actuator Ctrl Circ High Bank 1",
  p2655: "A Rocker Arm Actuator Ctrl Circ/Open Bank 2",
  p2656: "A Rocker Arm Actuator Sys Performance or Stuck Off Bank 2",
  p2657: "A Rocker Arm Actuator Sys Stuck On Bank 2",
  p2658: "A Rocker Arm Actuator Ctrl Circ Low Bank 2",
  p2659: "A Rocker Arm Actuator Ctrl Circ High Bank 2",
  p2660: "B Rocker Arm Actuator Ctrl Circ/Open Bank 2",
  p2661: "B Rocker Arm Actuator Sys Performance or Stuck Off Bank 2",
  p2662: "B Rocker Arm Actuator Sys Stuck On Bank 2",
  p2663: "B Rocker Arm Actuator Ctrl Circ Low Bank 2",
  p2664: "B Rocker Arm Actuator Ctrl Circ High Bank 2",
  p2665: "Fuel Shutoff Valve B Ctrl Circ/Open",
  p2666: "Fuel Shutoff Valve B Ctrl Circ Low",
  p2667: "Fuel Shutoff Valve B Ctrl Circ High",
  p2668: "Fuel Mode Indicator Lamp Ctrl Circ",
  p2669: "Actuator Supply Voltage B Circ /Open",
  p2670: "Actuator Supply Voltage B Circ Low",
  p2671: "Actuator Supply Voltage B Circ High",
  p2700: "Trans Friction Element A Apply Time Range/Performance",
  p2701: "Trans Friction Element B Apply Time Range/Performance",
  p2702: "Trans Friction Element C Apply Time Range/Performance",
  p2703: "Trans Friction Element D Apply Time Range/Performance",
  p2704: "Trans Friction Element E Apply Time Range/Performance",
  p2705: "Trans Friction Element F Apply Time Range/Performance",
  p2706: "Shift Solenoid F",
  p2707: "Shift Solenoid F Performance or Stuck Off",
  p2708: "Shift Solenoid F Stuck On",
  p2709: "Shift Solenoid F Electrical",
  p2710: "Shift Solenoid F Interm",
  p2711: "Unexpected Mechanical Gear Disengagement",
  p2712: "Hydraulic Power Unit Leakage",
  p2713: "Press Ctrl Solenoid D",
  p2714: "Press Ctrl Solenoid D Performance or Stuck Off",
  p2715: "Press Ctrl Solenoid D Stuck On",
  p2716: "Press Ctrl Solenoid D Electrical",
  p2717: "Press Ctrl Solenoid D Interm",
  p2718: "Press Ctrl Solenoid D Ctrl Circ / Open",
  p2719: "Press Ctrl Solenoid D Ctrl Circ Range/Performance",
  p2720: "Press Ctrl Solenoid D Ctrl Circ Low",
  p2721: "Press Ctrl Solenoid D Ctrl Circ High",
  p2722: "Press Ctrl Solenoid E",
  p2723: "Press Ctrl Solenoid E Performance or Stuck Off",
  p2724: "Press Ctrl Solenoid E Stuck On",
  p2725: "Press Ctrl Solenoid E Electrical",
  p2726: "Press Ctrl Solenoid E Interm",
  p2727: "Press Ctrl Solenoid E Ctrl Circ / Open",
  p2728: "Press Ctrl Solenoid E Ctrl Circ Range/Performance",
  p2729: "Press Ctrl Solenoid E Ctrl Circ Low",
  p2730: "Press Ctrl Solenoid E Ctrl Circ High",
  p2731: "Press Ctrl Solenoid F",
  p2732: "Press Ctrl Solenoid F Performance or Stuck Off",
  p2733: "Press Ctrl Solenoid F Stuck On",
  p2734: "Press Ctrl Solenoid F Electrical",
  p2735: "Press Ctrl Solenoid F Interm",
  p2736: "Press Ctrl Solenoid F Ctrl Circ/Open",
  p2737: "Press Ctrl Solenoid F Ctrl Circ Range/Performance",
  p2738: "Press Ctrl Solenoid F Ctrl Circ Low",
  p2739: "Press Ctrl Solenoid F Ctrl Circ High",
  p2740: "Trans Fluid Temp SensorB Circ",
  p2741: "Trans Fluid Temp SensorB Circ Range Performance",
  p2742: "Trans Fluid Temp SensorB Circ Low",
  p2743: "Trans Fluid Temp SensorB Circ High",
  p2744: "Trans Fluid Temp SensorB Circ Interm",
  p2745: "Intermediate Shaft Speed SensorB Circ",
  p2746: "Intermediate Shaft Speed SensorB Circ Range/Performance",
  p2747: "Intermediate Shaft Speed SensorB Circ No Signal",
  p2748: "Intermediate Shaft Speed SensorB Circ Interm",
  p2749: "Intermediate Shaft Speed Sensor C Circ",
  p2750: "Intermediate Shaft Speed Sensor C Circ Range/Performance",
  p2751: "Intermediate Shaft Speed Sensor C Circ No Signal",
  p2752: "Intermediate Shaft Speed Sensor C Circ Interm",
  p2753: "Trans Fluid Cooler Ctrl Circ/Open",
  p2754: "Trans Fluid Cooler Ctrl Circ Low",
  p2755: "Trans Fluid Cooler Ctrl Circ High",
  p2756: "Torq Conv Clutch Press Ctrl Solenoid",
  p2757: "Torq Conv Clutch Press Ctrl Solenoid Ctrl Circ Performance or Stuck Off",
  p2758: "Torq Conv Clutch Press Ctrl Solenoid Ctrl Circ Stuck On",
  p2759: "Torq Conv Clutch Press Ctrl Solenoid Ctrl Circ Electrical",
  p2760: "Torq Conv Clutch Press Ctrl Solenoid Ctrl Circ Interm",
  p2761: "Torq Conv Clutch Press Ctrl Solenoid Ctrl Circ/Open",
  p2762: "Torq Conv Clutch Press Ctrl Solenoid Ctrl Circ Range/Performance",
  p2763: "Torq Conv Clutch Press Ctrl Solenoid Ctrl Circ High",
  p2764: "Torq Conv Clutch Press Ctrl Solenoid Ctrl Circ Low",
  p2765: "Input/Turbine Speed SensorB Circ",
  p2766: "Input/Turbine Speed SensorB Circ Range/Performance",
  p2767: "Input/Turbine Speed SensorB Circ No Signal",
  p2768: "Input/Turbine Speed SensorB Circ Interm",
  p2769: "Torq Conv Clutch Circ Low",
  p2770: "Torq Conv Clutch Circ High",
  p2771: "4WD Low Switch Circ",
  p2772: "4WD Low Switch Circ Range/Performance",
  p2773: "4WD Low Switch Circ Low",
  p2774: "4WD Low Switch Circ High",
  p2775: "Upshift Switch Circ Range/Performance",
  p2776: "Upshift Switch Circ Low",
  p2777: "Upshift Switch Circ High",
  p2778: "Upshift Switch Circ Interm/Erratic",
  p2779: "Downshift Switch Circ Range/Performance",
  p2780: "Downshift Switch Circ Low",
  p2781: "Downshift Switch Circ High",
  p2782: "Downshift Switch Circ Interm/Erratic",
  p2783: "Torq Conv Temp Too High",
  p2784: "Input/Turbine Speed SensorA/B Correlation",
  p2785: "Clutch Actuator Temp Too High",
  p2786: "Gear Shift Actuator Temp Too High",
  p2787: "Clutch Temp Too High",
  p2788: "Auto Shift Manual Adaptive Learning at Limit",
  p2789: "Clutch Adaptive Learning at Limit",
  p2790: "Gate Select Direction Circ",
  p2791: "Gate Select Direction Circ Low",
  p2792: "Gate Select Direction Circ High",
  p2793: "Gear Shift Direction Circ",
  p2794: "Gear Shift Direction Circ Low",
  p2795: "Gear Shift Direction Circ High",
  p2A00: "O2 Sensor Circ Range/Performance Bank 1 Sensor 1",
  p2A01: "O2 Sensor Circ Range/Performance Bank 1 Sensor 2",
  p2A02: "O2 Sensor Circ Range/Performance Bank 1 Sensor 3",
  p2A03: "O2 Sensor Circ Range/Performance Bank 2 Sensor 1",
  p2A04: "O2 Sensor Circ Range/Performance Bank 2 Sensor 2",
  p2A05: "O2 Sensor Circ Range/Performance Bank 2 Sensor 3",
  p3400: "Cylinder Deactivation Sys Bank 1",
  p3401: "Cyl1 Deactivation/Intake Valve Ctrl Circ/Open",
  p3402: "Cyl1 Deactivation/Intake Valve Ctrl Performance",
  p3403: "Cyl1 Deactivation/Intake Valve Ctrl Circ Low",
  p3404: "Cyl1 Deactivation/Intake Valve Ctrl Circ High",
  p3405: "Cyl1 Exhaust Valve Ctrl Circ/Open",
  p3406: "Cyl1 Exhaust Valve Ctrl Performance",
  p3407: "Cyl1 Exhaust Valve Ctrl Circ Low",
  p3408: "Cyl1 Exhaust Valve Ctrl Circ High",
  p3409: "Cyl2 Deactivation/Intake Valve Ctrl Circ/Open",
  p3410: "Cyl2 Deactivation/Intake Valve Ctrl Performance",
  p3411: "Cyl2 Deactivation/Intake Valve Ctrl Circ Low",
  p3412: "Cyl2 Deactivation/Intake Valve Ctrl Circ High",
  p3413: "Cyl2 Exhaust Valve Ctrl Circ/Open",
  p3414: "Cyl2 Exhaust Valve Ctrl Performance",
  p3415: "Cyl2 Exhaust Valve Ctrl Circ Low",
  p3416: "Cyl2 Exhaust Valve Ctrl Circ High",
  p3417: "Cyl3 Deactivation/Intake Valve Ctrl Circ/Open",
  p3418: "Cyl3 Deactivation/Intake Valve Ctrl Performance",
  p3419: "Cyl3 Deactivation/Intake Valve Ctrl Circ Low",
  p3420: "Cyl3 Deactivation/Intake Valve Ctrl Circ High",
  p3421: "Cyl3 Exhaust Valve Ctrl Circ/Open",
  p3422: "Cyl3 Exhaust Valve Ctrl Performance",
  p3423: "Cyl3 Exhaust Valve Ctrl Circ Low",
  p3424: "Cyl3 Exhaust Valve Ctrl Circ High",
  p3425: "Cyl4 Deactivation/Intake Valve Ctrl Circ/Open",
  p3426: "Cyl4 Deactivation/Intake Valve Ctrl Performance",
  p3427: "Cyl4 Deactivation/Intake Valve Ctrl Circ Low",
  p3428: "Cyl4 Deactivation/Intake Valve Ctrl Circ High",
  p3429: "Cyl4 Exhaust Valve Ctrl Circ/Open",
  p3430: "Cyl4 Exhaust Valve Ctrl Performance",
  p3431: "Cyl4 Exhaust Valve Ctrl Circ Low",
  p3432: "Cyl4 Exhaust Valve Ctrl Circ High",
  p3433: "Cyl5 Deactivation/Intake Valve Ctrl Circ/Open",
  p3434: "Cyl5 Deactivation/Intake Valve Ctrl Performance",
  p3435: "Cyl5 Deactivation/Intake Valve Ctrl Circ Low",
  p3436: "Cyl5 Deactivation/Intake Valve Ctrl Circ High",
  p3437: "Cyl5 Exhaust Valve Ctrl Circ/Open",
  p3438: "Cyl5 Exhaust Valve Ctrl Performance",
  p3439: "Cyl5 Exhaust Valve Ctrl Circ Low",
  p3440: "Cyl5 Exhaust Valve Ctrl Circ High",
  p3441: "Cyl6 Deactivation/Intake Valve Ctrl Circ/Open",
  p3442: "Cyl6 Deactivation/Intake Valve Ctrl Performance",
  p3443: "Cyl6 Deactivation/Intake Valve Ctrl Circ Low",
  p3444: "Cyl6 Deactivation/Intake Valve Ctrl Circ High",
  p3445: "Cyl6 Exhaust Valve Ctrl Circ/Open",
  p3446: "Cyl6 Exhaust Valve Ctrl Performance",
  p3447: "Cyl6 Exhaust Valve Ctrl Circ Low",
  p3448: "Cyl6 Exhaust Valve Ctrl Circ High",
  p3449: "Cyl7 Deactivation/Intake Valve Ctrl Circ/Open",
  p3450: "Cyl7 Deactivation/Intake Valve Ctrl Performance",
  p3451: "Cyl7 Deactivation/Intake Valve Ctrl Circ Low",
  p3452: "Cyl7 Deactivation/Intake Valve Ctrl Circ High",
  p3453: "Cyl7 Exhaust Valve Ctrl Circ/Open",
  p3454: "Cyl7 Exhaust Valve Ctrl Performance",
  p3455: "Cyl7 Exhaust Valve Ctrl Circ Low",
  p3456: "Cyl7 Exhaust Valve Ctrl Circ High",
  p3457: "Cyl8 Deactivation/Intake Valve Ctrl Circ/Open",
  p3458: "Cyl8 Deactivation/Intake Valve Ctrl Performance",
  p3459: "Cyl8 Deactivation/Intake Valve Ctrl Circ Low",
  p3460: "Cyl8 Deactivation/Intake Valve Ctrl Circ High",
  p3461: "Cyl8 Exhaust Valve Ctrl Circ/Open",
  p3462: "Cyl8 Exhaust Valve Ctrl Performance",
  p3463: "Cyl8 Exhaust Valve Ctrl Circ Low",
  p3464: "Cyl8 Exhaust Valve Ctrl Circ High",
  p3465: "Cyl9 Deactivation/Intake Valve Ctrl Circ/Open",
  p3466: "Cyl9 Deactivation/Intake Valve Ctrl Performance",
  p3467: "Cyl9 Deactivation/Intake Valve Ctrl Circ Low",
  p3468: "Cyl9 Deactivation/Intake Valve Ctrl Circ High",
  p3469: "Cyl9 Exhaust Valve Ctrl Circ/Open",
  p3470: "Cyl9 Exhaust Valve Ctrl Performance",
  p3471: "Cyl9 Exhaust Valve Ctrl Circ Low",
  p3472: "Cyl9 Exhaust Valve Ctrl Circ High",
  p3473: "Cyl10 Deactivation/Intake Valve Ctrl Circ/Open",
  p3474: "Cyl10 Deactivation/Intake Valve Ctrl Performance",
  p3475: "Cyl10 Deactivation/Intake Valve Ctrl Circ Low",
  p3476: "Cyl10 Deactivation/Intake Valve Ctrl Circ High",
  p3477: "Cyl10 Exhaust Valve Ctrl Circ/Open",
  p3478: "Cyl10 Exhaust Valve Ctrl Performance",
  p3479: "Cyl10 Exhaust Valve Ctrl Circ Low",
  p3480: "Cyl10 Exhaust Valve Ctrl Circ High",
  p3481: "Cyl11 Deactivation/Intake Valve Ctrl Circ/Open",
  p3482: "Cyl11 Deactivation/Intake Valve Ctrl Performance",
  p3483: "Cyl11 Deactivation/Intake Valve Ctrl Circ Low",
  p3484: "Cyl11 Deactivation/Intake Valve Ctrl Circ High",
  p3485: "Cyl11 Exhaust Valve Ctrl Circ/Open",
  p3486: "Cyl11 Exhaust Valve Ctrl Performance",
  p3487: "Cyl11 Exhaust Valve Ctrl Circ Low",
  p3488: "Cyl11 Exhaust Valve Ctrl Circ High",
  p3489: "Cyl12 Deactivation/Intake Valve Ctrl Circ/Open",
  p3490: "Cyl12 Deactivation/Intake Valve Ctrl Performance",
  p3491: "Cyl12 Deactivation/Intake Valve Ctrl Circ Low",
  p3492: "Cyl12 Deactivation/Intake Valve Ctrl Circ High",
  p3493: "Cyl12 Exhaust Valve Ctrl Circ/Open",
}

dtc.each do |k,v|
  c = Code.where(code: k).first_or_initialize
  c.description = v
  c.save
  puts k
end