aws:
  bucket: ridesnap-dev
  address: https://ridesnap-dev.s3.amazonaws.com

carvoyant:
  base_url: https://sandbox-api.carvoyant.com
  auth_url: https://sandbox-auth.carvoyant.com/OAuth/authorize
  token_path: /sandbox/oauth/token
  api_version: /sandbox/api
  callback_url: https://ridesnap.dev/auth/carvoyant/callback #lvh.me:3000
  client_id: 3z4qenxtm4vjzu5fhtpr88x9
  secret: SxJHyVrfZq

fresh_cars: false