aws:
  bucket: ridesnap-dev
  address: https://ridesnap-dev.s3.amazonaws.com

carvoyant:
  base_url: https://sandbox-api.carvoyant.com
  token_url: /sandbox/oauth/token
  api_version: /sandbox/api
  callback_url: lvh.me:3000
  client_id: 3z4qenxtm4vjzu5fhtpr88x9
  secret: SxJHyVrfZq

fresh_cars: false